'use strict';
const Core=window.FreshnessCore;
const $=id=>document.getElementById(id);
const state={indicator:'pH',factorCount:1,design:null,templateRows:[],rawRows:[],analysis:null,currentStep:1,style:'nature',selectedAnalyses:[]};
const PALETTES={
 nature:{name:'Nature-inspired',colors:['#3C5488','#E64B35','#00A087','#4DBBD5','#F39B7F','#8491B4','#91D1C2','#7E6148'],font:'Arial'},
 science:{name:'Science-inspired',colors:['#3B4992','#EE0000','#008B45','#631879','#008280','#BB0021','#5F559B','#A20056'],font:'Arial'},
 cell:{name:'Cell-inspired',colors:['#1B9E77','#D95F02','#7570B3','#E7298A','#66A61E','#E6AB02','#A6761D','#666666'],font:'Helvetica'},
 acs:{name:'ACS / color-safe',colors:['#0072B2','#E69F00','#009E73','#D55E00','#CC79A7','#56B4E9','#000000','#F0E442'],font:'Arial'},
 pastel:{name:'Soft editorial',colors:['#4C78A8','#F58518','#54A24B','#E45756','#72B7B2','#B279A2','#FF9DA6','#9D755D'],font:'Arial'},
 mono:{name:'Monochrome',colors:['#111111','#555555','#888888','#BBBBBB','#333333','#777777'],font:'Arial'}
};
const METRIC_LABELS={pH:'pH',L:'L*',a:'a*',b:'b*',C:'C*',h:'h°',DeltaE:'ΔE'};

function init(){bind();renderFactorPreviews();renderStylePresets();restore();showHome();}
function bind(){
 $('goHome').onclick=showHome;
 document.querySelectorAll('.metric-card').forEach(b=>b.onclick=()=>selectIndicator(b.dataset.indicator));
 document.querySelectorAll('.factor-count').forEach(b=>b.onclick=()=>setFactorCount(Number(b.dataset.count)));
 ['factor1Name','factor1Type','factor1Unit','factor1Levels','factor2Name','factor2Type','factor2Unit','factor2Levels','parallelCount','measureCount','experimentName','sampleName','outputLanguage','defaultError','missingStrategy'].forEach(id=>$(id).addEventListener('input',()=>{renderFactorPreviews();updateRepeatText();persist()}));
 document.querySelectorAll('.next-button').forEach(b=>b.onclick=()=>goStep(Number(b.dataset.next)));
 document.querySelectorAll('.prev-button').forEach(b=>b.onclick=()=>goStep(Number(b.dataset.prev)));
 document.querySelectorAll('.step').forEach(b=>b.onclick=()=>goStep(Number(b.dataset.step)));
 $('downloadCsv').onclick=downloadTemplateCsv;$('downloadXlsx').onclick=downloadTemplateXlsx;
 $('chooseFile').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>e.target.files[0]&&handleFile(e.target.files[0]);$('loadDemo').onclick=loadDemo;
 const dz=$('dropZone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0]));
 $('runSelectedAnalysis').onclick=runSelectedAnalyses;
 ['chartType','chartMetric','chartLanguage','chartError','figureWidth','showRawPoints'].forEach(id=>$(id).addEventListener('change',renderChart));
 $('exportSvg').onclick=exportSvg;$('exportPng').onclick=exportPng;$('exportResults').onclick=exportResultsCsv;$('finishProject').onclick=()=>{persist();toast('项目已保存在当前设备')};
 $('uiLanguage').onchange=()=>toast('界面双语翻译将在后续版本完成；当前已支持中英文图表输出。');
}
function showHome(){$('homeView').classList.add('active');$('workspaceView').classList.remove('active')}
function selectIndicator(ind){if(!['pH','color'].includes(ind)){toast('该指标将在 pH 与色泽流程稳定后接入');return}state.indicator=ind;$('homeView').classList.remove('active');$('workspaceView').classList.add('active');$('currentIndicatorLabel').textContent=ind==='pH'?'pH 模块':'色泽模块';$('experimentName').value=ind==='pH'?'肉制品 pH 实验':'肉制品色泽实验';updateMetricOptions();goStep(1);persist()}
function setFactorCount(n){state.factorCount=n;document.querySelectorAll('.factor-count').forEach(b=>b.classList.toggle('active',Number(b.dataset.count)===n));$('factor2Card').classList.toggle('hidden',n!==2);renderFactorPreviews();updateRepeatText();persist()}
function safeLevels(id){return Core.parseLevels($(id).value)}
function factorHeader(i,name,unit){return `Factor${i}_${name}${unit?`(${unit})`:''}`}
function getDesign(){const f1={name:$('factor1Name').value.trim()||'因素A',type:$('factor1Type').value,unit:$('factor1Unit').value.trim(),levels:safeLevels('factor1Levels')};f1.header=factorHeader(1,f1.name,f1.unit);const f2={name:$('factor2Name').value.trim()||'因素B',type:$('factor2Type').value,unit:$('factor2Unit').value.trim(),levels:safeLevels('factor2Levels')};f2.header=factorHeader(2,f2.name,f2.unit);return{experimentName:$('experimentName').value.trim(),sampleName:$('sampleName').value.trim(),indicator:state.indicator,factorCount:state.factorCount,factors:[f1,f2],parallelCount:Math.max(2,Number($('parallelCount').value)||3),measureCount:Math.max(1,Number($('measureCount').value)||1),outputLanguage:$('outputLanguage').value,defaultError:$('defaultError').value,missingStrategy:$('missingStrategy').value}}
function renderFactorPreviews(){for(const i of [1,2]){const box=$(`factor${i}Preview`),levels=safeLevels(`factor${i}Levels`);box.innerHTML=levels.slice(0,16).map(x=>`<span>${esc(x)}</span>`).join('')+(levels.length>16?`<span>+${levels.length-16}</span>`:'')}const d=getDesign();$('designSummaryBadge').textContent=d.factorCount===1?'单因素设计':'双因素析因设计';}
function updateRepeatText(){const p=Math.max(2,Number($('parallelCount').value)||3),m=Math.max(1,Number($('measureCount').value)||1);$('repeatExplanation').textContent=`每个条件 ${p} 个独立平行样品，每个样品测 ${m} 次；技术重复先求样品均值，统计 n=${p}。`}
function validateDesign(d){const e=[];if(!d.experimentName)e.push('请填写实验名称。');if(!d.factors[0].levels.length)e.push('因素A至少需要1个水平。');if(d.factorCount===2&&!d.factors[1].levels.length)e.push('因素B至少需要1个水平。');if(new Set(d.factors[0].levels).size!==d.factors[0].levels.length)e.push('因素A水平存在重复。');if(d.factorCount===2&&new Set(d.factors[1].levels).size!==d.factors[1].levels.length)e.push('因素B水平存在重复。');return e}
function goStep(n){if(n>=2){const d=getDesign(),e=validateDesign(d);if(e.length){toast(e[0]);return}state.design=d;buildTemplate();renderAnalysisCards();updateMetricOptions()}state.currentStep=n;document.querySelectorAll('.wizard-page').forEach(p=>p.classList.toggle('active',Number(p.dataset.page)===n));document.querySelectorAll('.step').forEach(s=>{const k=Number(s.dataset.step);s.classList.toggle('active',k===n);s.classList.toggle('done',k<n)});if(n===5)renderChart();window.scrollTo({top:72,behavior:'smooth'});persist()}
function combinations(d){const out=[];for(const a of d.factors[0].levels){if(d.factorCount===1)out.push([a,'']);else for(const b of d.factors[1].levels)out.push([a,b])}return out}
function metricHeaders(){return state.indicator==='pH'?['pH']:['L*','a*','b*']}
function factorDisplayHeader(f){return `${f.name}${f.unit?`(${f.unit})`:''}`}
function toUserTemplateRows(){const d=state.design||getDesign();return state.templateRows.map(r=>{const out={'样品编号':r.SampleID};out[factorDisplayHeader(d.factors[0])]=r[d.factors[0].header];if(d.factorCount===2)out[factorDisplayHeader(d.factors[1])]=r[d.factors[1].header];out['平行样品编号']=r.ParallelSample;out['测量重复编号']=r.MeasureReplicate;for(const h of metricHeaders())out[h]=r[h];out['是否纳入']=r.Include;out['备注']=r.Notes;return out})}
function buildTemplate(){const d=state.design||getDesign(),rows=[];for(const [a,b] of combinations(d))for(let p=1;p<=d.parallelCount;p++)for(let m=1;m<=d.measureCount;m++){const r={SampleID:`${String(a).replace(/\s/g,'')}${d.factorCount===2?'-'+String(b).replace(/\s/g,''):''}-S${p}${d.measureCount>1?'-M'+m:''}`};r[d.factors[0].header]=a;if(d.factorCount===2)r[d.factors[1].header]=b;r.ParallelSample=p;r.MeasureReplicate=m;for(const h of metricHeaders())r[h]='';r.Include='是';r.Notes='';rows.push(r)}state.templateRows=rows;$('templateRowBadge').textContent=`预计 ${rows.length} 行`;$('templateSummary').innerHTML=[`指标：${state.indicator==='pH'?'pH':'色泽 L* a* b*'}`,`${d.factorCount===1?'单因素':'双因素'}`,`${combinations(d).length} 个条件组合`,`${d.parallelCount} 平行 × ${d.measureCount} 次测量`].map(x=>`<span class="summary-pill">${esc(x)}</span>`).join('');renderTable($('templatePreviewTable'),toUserTemplateRows().slice(0,12));}
function renderTable(table,rows){if(!rows.length){table.innerHTML='<tbody><tr><td class="empty-cell">无数据</td></tr></tbody>';return}const heads=Object.keys(rows[0]);table.innerHTML=`<thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${heads.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody>`}
function designSheetRows(d){return[['项目','值'],['实验名称',d.experimentName],['样品名称',d.sampleName],['指标',d.indicator],['因素数量',d.factorCount],['因素A名称',d.factors[0].name],['因素A类型',d.factors[0].type],['因素A单位',d.factors[0].unit],['因素A水平',d.factors[0].levels.join(', ')],['因素B名称',d.factorCount===2?d.factors[1].name:''],['因素B类型',d.factorCount===2?d.factors[1].type:''],['因素B单位',d.factorCount===2?d.factors[1].unit:''],['因素B水平',d.factorCount===2?d.factors[1].levels.join(', '):''],['独立平行数',d.parallelCount],['每样品测量次数',d.measureCount],['说明','本页由软件自动生成，请勿修改。若实验设计变化，请返回软件重新生成模板。']]}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadTemplateCsv(){buildTemplate();const rows=toUserTemplateRows(),heads=Object.keys(rows[0]),text='\ufeff'+[heads.join(','),...rows.map(r=>heads.map(h=>csvEscape(r[h])).join(','))].join('\r\n');downloadBlob(new Blob([text],{type:'text/csv;charset=utf-8'}),fileBase()+'_数据填写模板.csv');toast('CSV 数据填写模板已生成')}
function downloadTemplateXlsx(){buildTemplate();if(!window.XLSX){toast('Excel组件未加载，请先下载 CSV；最终桌面版会内置组件。');return}const rows=toUserTemplateRows(),wb=XLSX.utils.book_new(),dataWs=XLSX.utils.json_to_sheet(rows),designWs=XLSX.utils.aoa_to_sheet(designSheetRows(state.design)),fillable=state.indicator==='pH'?'pH':'L*、a*、b*',guide=XLSX.utils.aoa_to_sheet([['食品实验数据分析平台——模板填写说明'],['请直接打开第一个工作表“数据填写”。'],[`本次只需填写：${fillable} 数据列；“备注”可选填。`],['样品编号、因素水平、平行样品编号和测量重复编号均已自动生成，请勿修改。'],['每一行代表一个独立样品的一次仪器测量。'],['不要填写平均值、标准差或“平均值±标准差”，只填写单个原始数值。'],['“是否纳入”默认填“是”；排除数据时改为“否”，并在备注中说明原因。'],['如需更改因素、水平、组数或重复数，请返回软件重新生成模板，不要直接改项目配置。']]);dataWs['!cols']=Object.keys(rows[0]).map(h=>({wch:h==='备注'?28:h==='样品编号'?22:h.includes('编号')?14:Math.max(12,Math.min(22,String(h).length*2+4))}));dataWs['!autofilter']={ref:dataWs['!ref']};designWs['!cols']=[{wch:20},{wch:48}];guide['!cols']=[{wch:92}];XLSX.utils.book_append_sheet(wb,dataWs,'数据填写');XLSX.utils.book_append_sheet(wb,designWs,'项目配置（勿改）');XLSX.utils.book_append_sheet(wb,guide,'填写说明');XLSX.writeFile(wb,fileBase()+'_可填写模板.xlsx');toast(`Excel 模板已生成：打开“数据填写”，只填 ${fillable} 列`)}
function fileBase(){return(state.design?.experimentName||'实验').replace(/[\\/:*?"<>|]/g,'_')+'_'+(state.indicator==='pH'?'pH':'色泽')}
async function handleFile(file){try{let rows;if(file.name.toLowerCase().endsWith('.csv'))rows=parseCsv(await file.text());else{if(!window.XLSX)throw new Error('Excel组件未加载，请使用 CSV 或联网重新打开。');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),name=wb.SheetNames.includes('数据填写')?'数据填写':wb.SheetNames.includes('原始数据')?'原始数据':wb.SheetNames[0];rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:true})}processImported(rows,file.name)}catch(e){showValidation([e.message],[]);$('importBadge').textContent='导入失败';toast(e.message)}}
function mapImportedRows(rows){const d=state.design||getDesign();return rows.map(r=>{const keys=Object.keys(r),findFactor=(f,index)=>keys.find(k=>k===`Factor${index}`||k.startsWith(`Factor${index}_`)||k===f.header||k===factorDisplayHeader(f)||k===f.name||k.startsWith(`${f.name}(`)),f1k=findFactor(d.factors[0],1)||d.factors[0].header,f2k=findFactor(d.factors[1],2)||d.factors[1].header;return{...r,Factor1:r[f1k]??'',Factor2:d.factorCount===2?(r[f2k]??''):'',ParallelSample:r.ParallelSample??r['平行样品']??r['平行样品编号']??r['独立平行编号'],MeasureReplicate:r.MeasureReplicate??r['测量重复']??r['测量重复编号']??r['测量编号']??1,pH:r.pH??r['pH值']??r['pH（请填写）'],L:r.L??r['L*'],a:r.a??r['a*'],b:r.b??r['b*'],Include:r.Include??r['纳入']??r['是否纳入']??'是',Notes:r.Notes??r['备注']??''}})}
function processImported(rows,name){state.rawRows=mapImportedRows(rows);const normalized=Core.normalizeRows(state.rawRows,state.design,state.indicator);state.analysis=Core.analyze(normalized,state.design,state.indicator);showValidation(state.analysis.validation.errors,state.analysis.validation.warnings);$('importBadge').textContent=`${name} · ${rows.length}行`;renderRawPreview(normalized);const ok=state.analysis.validation.valid;$('toAnalysis').disabled=!ok;$('exportSvg').disabled=!ok;$('exportPng').disabled=!ok;$('exportResults').disabled=!ok;if(ok){renderAnalysisCards();renderChart();toast('数据校验完成')}persist()}
function showValidation(errors,warnings){const box=$('validationBox');box.className='validation-box';let html='';if(!errors.length&&!warnings.length)html='<div class="issue success">✓ 数据结构完整，可以分析。</div>';html+=errors.map(x=>`<div class="issue error">${esc(x)}</div>`).join('');html+=warnings.map(x=>`<div class="issue warning">${esc(x)}</div>`).join('');box.innerHTML=html||'<div class="issue success">✓ 校验完成。</div>'}
function renderRawPreview(rows){const display=rows.slice(0,80).map(r=>state.indicator==='pH'?{Factor1:r.Factor1,Factor2:r.Factor2,ParallelSample:r.ParallelSample,MeasureReplicate:r.MeasureReplicate,pH:r.pH}:{Factor1:r.Factor1,Factor2:r.Factor2,ParallelSample:r.ParallelSample,MeasureReplicate:r.MeasureReplicate,'L*':r.L,'a*':r.a,'b*':r.b});renderTable($('rawPreview'),display)}
function loadDemo(){state.design=getDesign();const rows=[],noise=[-.03,.01,.02];for(const [ai,a] of state.design.factors[0].levels.entries()){const bLevels=state.design.factorCount===2?state.design.factors[1].levels:[''];for(const [bi,b] of bLevels.entries())for(let p=1;p<=state.design.parallelCount;p++)for(let m=1;m<=state.design.measureCount;m++){const n=noise[(p+m-2)%noise.length];if(state.indicator==='pH')rows.push({Factor1:a,Factor2:b,ParallelSample:p,MeasureReplicate:m,pH:5.58+ai*.04+bi*.08+n,Include:'是'});else rows.push({Factor1:a,Factor2:b,ParallelSample:p,MeasureReplicate:m,L:52-ai*.45+bi*.3+n*3,a:13-ai*.5-bi*.3+n*2,b:8+ai*.25+bi*.2+n,Include:'是'})}}processImported(rows,'内置演示数据')}
function parseCsv(text){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const delim=lines[0].includes('\t')?'\t':',';const split=line=>{let a=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&q){v+='"';i++}else if(c==='"')q=!q;else if(c===delim&&!q){a.push(v);v=''}else v+=c}a.push(v);return a};const h=split(lines[0]);return lines.slice(1).map(l=>Object.fromEntries(h.map((x,i)=>[x,split(l)[i]??''])))}
function updateMetricOptions(){const opts=state.indicator==='pH'?[['pH','pH']]:[['L','L*'],['a','a*'],['b','b*'],['C','C*'],['h','h°'],['DeltaE','ΔE']];$('chartMetric').innerHTML=opts.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}
function renderAnalysisCards(){const d=state.design||getDesign(),numericA=d.factors[0].type==='numeric';const methods=[
 {id:'descriptive',title:'描述统计与论文结果表',desc:'Mean、SD、SE、95% CI、CV、范围与样品级数据。',tags:['基础','已实现'],rec:true,impl:true},
 {id:'oneway',title:'单因素方差分析',desc:'比较一个因素多个水平；输出 F、P 和 η²。',tags:['One-way ANOVA','已实现'],rec:d.factorCount===1,impl:d.factorCount===1},
 {id:'twoway',title:'双因素方差分析与交互作用',desc:'分别检验因素A、因素B和 A×B 交互作用。',tags:['Two-way ANOVA','已实现'],rec:d.factorCount===2,impl:d.factorCount===2},
 {id:'trend',title:'剂量/时间趋势分析',desc:'数值型因素的线性趋势、斜率、R²和趋势显著性。',tags:['Regression','已实现'],rec:numericA,impl:numericA},
 {id:'posthoc',title:'多重比较与显著性字母',desc:'Tukey、Duncan、LSD、Bonferroni；按同一时间比较组别或同组比较水平。',tags:['Post hoc','下一阶段'],rec:true,impl:false},
 {id:'assumption',title:'正态性与方差齐性',desc:'Shapiro–Wilk、Levene/Brown–Forsythe，并据此提示参数或非参数检验。',tags:['前提检验','下一阶段'],rec:true,impl:false},
 {id:'nonparametric',title:'非参数检验',desc:'Kruskal–Wallis、Mann–Whitney、Dunn 多重比较。',tags:['稳健分析','下一阶段'],rec:false,impl:false},
 {id:'outlier',title:'异常值与重复性诊断',desc:'标记可疑点、组内CV和技术重复差异；仅提示，不自动删除。',tags:['质量控制','下一阶段'],rec:true,impl:false},
 {id:'effect',title:'效应量与置信区间',desc:'η²、偏η²、组间差值及置信区间，避免只报告P值。',tags:['论文增强','部分实现'],rec:true,impl:true}
 ];$('analysisCards').innerHTML=methods.map(m=>`<label class="analysis-card ${m.rec?'recommended':''}"><input type="checkbox" value="${m.id}" ${m.rec?'checked':''}><h3>${m.title}</h3><p>${m.desc}</p>${m.tags.map(t=>`<span class="method-tag">${t}</span>`).join('')}</label>`).join('');$('analysisRecommendationBadge').textContent=d.factorCount===1?(numericA?'单因素 + 趋势':'单因素组间比较'):'双因素 + 交互作用'}
function runSelectedAnalyses(){if(!state.analysis?.results.length){toast('请先导入有效数据');return}const ids=[...document.querySelectorAll('#analysisCards input:checked')].map(x=>x.value),metric=$('chartMetric').value||'pH';let html='';if(ids.includes('descriptive'))html+=renderDescriptive(metric);if(ids.includes('oneway')&&state.design.factorCount===1){const a=Core.oneWayAnova(state.analysis.samples,metric);html+=anovaHtml('单因素 ANOVA',a)}if(ids.includes('twoway')&&state.design.factorCount===2){const a=Core.twoWayAnova(state.analysis.samples,metric,state.design);html+=twoWayHtml(a)}if(ids.includes('trend')&&state.design.factors[0].type==='numeric'){const r=Core.linearRegression(state.analysis.samples,metric);html+=trendHtml(r)}const pending=ids.filter(x=>['posthoc','assumption','nonparametric','outlier'].includes(x));if(pending.length)html+=`<div class="result-block"><h4>已选择但尚未接入计算引擎</h4><div class="issue warning">${pending.join('、')} 已进入开发清单；当前版本不会伪造这些结果。</div></div>`;$('analysisOutput').className='analysis-output';$('analysisOutput').innerHTML=html||'未选择可运行分析';}
function fmt(v,d=4){return v==null||!Number.isFinite(v)?'—':Number(v).toFixed(d)}function pFmt(p){return p==null?'—':p<.001?'P < 0.001':`P = ${p.toFixed(3)}`}
function renderDescriptive(metric){const items=state.analysis.results.map(r=>{const s=r[metric];return`<div class="result-item"><b>${esc(r.Factor1)}${r.Factor2?' × '+esc(r.Factor2):''}</b><span>${fmt(s?.mean,3)} ± ${fmt(s?.sd,3)} · n=${s?.n??0}</span></div>`}).join('');return`<div class="result-block"><h4>${METRIC_LABELS[metric]||metric} 描述统计（Mean ± SD）</h4><div class="result-list">${items}</div></div>`}
function anovaHtml(title,a){return`<div class="result-block"><h4>${title}</h4><div class="result-list"><div class="result-item"><b>F(${a.dfBetween}, ${a.dfWithin})</b><span>${fmt(a.F,3)}</span></div><div class="result-item"><b>显著性</b><span>${pFmt(a.p)}</span></div><div class="result-item"><b>η²</b><span>${fmt(a.eta2,3)}</span></div><div class="result-item"><b>样本数</b><span>N=${a.N}</span></div></div></div>`}
function twoWayHtml(a){if(a.error&&typeof a.error==='string')return`<div class="issue warning">${a.error}</div>`;const row=(name,x)=>`<div class="result-item"><b>${name}</b><span>F=${fmt(x.F,3)} · ${pFmt(x.p)} · partial η²=${fmt(x.partialEta2,3)}</span></div>`;return`<div class="result-block"><h4>双因素 ANOVA</h4><div class="result-list">${row(state.design.factors[0].name,a.A)}${row(state.design.factors[1].name,a.B)}${row('交互作用',a.interaction)}<div class="result-item"><b>单元重复</b><span>n=${a.nPerCell}</span></div></div></div>`}
function trendHtml(r){if(r.error)return`<div class="issue warning">${r.error}</div>`;return`<div class="result-block"><h4>线性趋势</h4><div class="result-list"><div class="result-item"><b>回归方程</b><span>y=${fmt(r.intercept,3)} + ${fmt(r.slope,4)}x</span></div><div class="result-item"><b>R²</b><span>${fmt(r.r2,3)}</span></div><div class="result-item"><b>趋势检验</b><span>${pFmt(r.p)}</span></div><div class="result-item"><b>观测数</b><span>N=${r.n}</span></div></div></div>`}
function renderStylePresets(){$('stylePresets').innerHTML=Object.entries(PALETTES).map(([id,p])=>`<button class="style-preset ${id===state.style?'active':''}" data-style="${id}"><b>${p.name}</b><span class="swatches">${p.colors.slice(0,6).map(c=>`<span style="background:${c}"></span>`).join('')}</span></button>`).join('');document.querySelectorAll('.style-preset').forEach(b=>b.onclick=()=>{state.style=b.dataset.style;renderStylePresets();renderChart()})}
function renderChart(){const box=$('chartCanvas');if(!state.analysis?.results.length){box.innerHTML='<div class="empty-chart">导入数据后生成图表</div>';return}const metric=$('chartMetric').value||'pH',d=state.design,pal=PALETTES[state.style],lang=$('chartLanguage').value,error=$('chartError').value,type=resolveChartType(),results=state.analysis.results.filter(r=>r[metric]?.mean!=null),seriesLevels=d.factorCount===2?d.factors[1].levels:[''];const W=960,H=530,M={l:88,r:28,t:55,b:78},iw=W-M.l-M.r,ih=H-M.t-M.b;const vals=results.flatMap(r=>{const s=r[metric],e=error==='sd'?s.sd:error==='se'?s.se:error==='ci'?s.ci:0;return[s.mean-(e||0),s.mean+(e||0)]}).filter(Number.isFinite);let ymin=Math.min(...vals),ymax=Math.max(...vals);if(ymin===ymax){ymin-=1;ymax+=1}const pad=(ymax-ymin)*.14;ymin-=pad;ymax+=pad;const y=v=>M.t+ih-(v-ymin)/(ymax-ymin)*ih;const levels=d.factors[0].levels,xCat=v=>M.l+(levels.indexOf(String(v))+.5)*iw/levels.length;const numeric=d.factors[0].type==='numeric',nums=levels.map(Number),xmin=Math.min(...nums),xmax=Math.max(...nums),xNum=v=>M.l+(Number(v)-xmin)/(xmax-xmin||1)*iw;const x=numeric&&['line','scatter','interaction'].includes(type)?xNum:xCat;let svg=`<svg id="paperChart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" style="font-family:${pal.font},Arial,sans-serif;background:white"><rect width="100%" height="100%" fill="white"/>`;
 for(let i=0;i<=5;i++){const v=ymin+(ymax-ymin)*i/5,yy=y(v);svg+=`<line x1="${M.l}" y1="${yy}" x2="${W-M.r}" y2="${yy}" stroke="#e8e8e8"/><text x="${M.l-12}" y="${yy+4}" text-anchor="end" font-size="12" fill="#333">${fmt(v,2)}</text>`}
 svg+=`<line x1="${M.l}" y1="${M.t}" x2="${M.l}" y2="${H-M.b}" stroke="#222" stroke-width="1.2"/><line x1="${M.l}" y1="${H-M.b}" x2="${W-M.r}" y2="${H-M.b}" stroke="#222" stroke-width="1.2"/>`;
 levels.forEach(l=>{const xx=x(l);svg+=`<line x1="${xx}" y1="${H-M.b}" x2="${xx}" y2="${H-M.b+5}" stroke="#222"/><text x="${xx}" y="${H-M.b+23}" text-anchor="middle" font-size="12">${escSvg(l)}</text>`});
 const title=lang==='en'?`${METRIC_LABELS[metric]||metric} response`:`${METRIC_LABELS[metric]||metric} 变化`;const xlabel=axisLabel(d.factors[0],lang),ylabel=METRIC_LABELS[metric]||metric;svg+=`<text x="${W/2}" y="27" text-anchor="middle" font-size="18" font-weight="600">${escSvg(title)}</text><text x="${W/2}" y="${H-22}" text-anchor="middle" font-size="14">${escSvg(xlabel)}</text><text x="22" y="${H/2}" text-anchor="middle" transform="rotate(-90 22 ${H/2})" font-size="14">${escSvg(ylabel)}</text>`;
 if(type==='bar'){const band=iw/levels.length,bw=Math.min(36,band/(seriesLevels.length+1));seriesLevels.forEach((sl,si)=>{results.filter(r=>r.Factor2===sl).forEach(r=>{const xx=xCat(r.Factor1)+(si-(seriesLevels.length-1)/2)*bw*1.15,yy=y(r[metric].mean),base=y(ymin),e=getErr(r[metric],error);svg+=`<rect x="${xx-bw/2}" y="${yy}" width="${bw}" height="${base-yy}" fill="${pal.colors[si%pal.colors.length]}" fill-opacity=".86"/>`;svg+=errorBarSvg(xx,r[metric].mean,e,y);if($('showRawPoints').checked)state.analysis.samples.filter(s=>s.Factor1===r.Factor1&&s.Factor2===r.Factor2).forEach((s,j)=>{svg+=`<circle cx="${xx+(j-(r.n-1)/2)*5}" cy="${y(s[metric])}" r="3" fill="#fff" stroke="#222"/>`})})})}else{seriesLevels.forEach((sl,si)=>{const rr=results.filter(r=>r.Factor2===sl),pts=rr.map(r=>`${x(r.Factor1)},${y(r[metric].mean)}`).join(' ');if(type!=='scatter')svg+=`<polyline fill="none" stroke="${pal.colors[si%pal.colors.length]}" stroke-width="2.3" points="${pts}"/>`;rr.forEach((r,ri)=>{const xx=x(r.Factor1),yy=y(r[metric].mean),shape=si%3;svg+=pointSvg(xx,yy,pal.colors[si%pal.colors.length],shape);svg+=errorBarSvg(xx,r[metric].mean,getErr(r[metric],error),y);if($('showRawPoints').checked)state.analysis.samples.filter(s=>s.Factor1===r.Factor1&&s.Factor2===r.Factor2).forEach((s,j)=>svg+=`<circle cx="${xx+(j-(r.n-1)/2)*4}" cy="${y(s[metric])}" r="2.2" fill="none" stroke="${pal.colors[si%pal.colors.length]}" opacity=".65"/>`)})})}
 if(seriesLevels.length>1){let lx=M.l;seriesLevels.forEach((sl,si)=>{svg+=`<line x1="${lx}" y1="46" x2="${lx+21}" y2="46" stroke="${pal.colors[si%pal.colors.length]}" stroke-width="2.5"/><circle cx="${lx+10}" cy="46" r="3.7" fill="${pal.colors[si%pal.colors.length]}"/><text x="${lx+27}" y="50" font-size="11">${escSvg(sl)}</text>`;lx+=Math.max(85,String(sl).length*9+50)})}svg+='</svg>';box.innerHTML=svg;$('chartTitleText').textContent=title;$('chartStyleText').textContent=`${pal.name} · RGB · ${$('figureWidth').value} mm`;$('exportSvg').disabled=false;$('exportPng').disabled=false;$('exportResults').disabled=false;}
function resolveChartType(){const v=$('chartType').value;if(v!=='auto')return v;const d=state.design;if(d.factorCount===2)return d.factors[0].type==='numeric'?'interaction':'bar';return d.factors[0].type==='numeric'?'line':'bar'}function getErr(s,e){return e==='sd'?s.sd:e==='se'?s.se:e==='ci'?s.ci:0}function errorBarSvg(x,meanValue,e,yfn){if(!e||!Number.isFinite(e)||!Number.isFinite(meanValue))return'';const top=yfn(meanValue+e),bot=yfn(meanValue-e);return`<line x1="${x}" y1="${top}" x2="${x}" y2="${bot}" stroke="#222"/><line x1="${x-5}" y1="${top}" x2="${x+5}" y2="${top}" stroke="#222"/><line x1="${x-5}" y1="${bot}" x2="${x+5}" y2="${bot}" stroke="#222"/>`}
function pointSvg(x,y,c,shape){if(shape===1)return`<rect x="${x-4}" y="${y-4}" width="8" height="8" fill="${c}"/>`;if(shape===2)return`<path d="M${x},${y-5} L${x+5},${y+4} L${x-5},${y+4} Z" fill="${c}"/>`;return`<circle cx="${x}" cy="${y}" r="4.2" fill="${c}"/>`}
function axisLabel(f,lang){const unit=f.unit?` (${f.unit})`:'';if(lang==='en'){const dict={'储藏时间':'Storage time','贮藏时间':'Storage time','添加量':'Addition level','温度':'Temperature','包装方式':'Packaging treatment'};return(dict[f.name]||f.name)+unit}return f.name+unit}
function exportSvg(){const svg=$('paperChart');if(!svg)return;downloadBlob(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'}),fileBase()+'_图.svg')}
function exportPng(){const svg=$('paperChart');if(!svg)return;const text=new XMLSerializer().serializeToString(svg),blob=new Blob([text],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const scale=3,canvas=document.createElement('canvas');canvas.width=960*scale;canvas.height=530*scale;const ctx=canvas.getContext('2d');ctx.scale(scale,scale);ctx.drawImage(img,0,0,960,530);canvas.toBlob(b=>downloadBlob(b,fileBase()+'_图.png'),'image/png');URL.revokeObjectURL(url)};img.src=url}
function exportResultsCsv(){if(!state.analysis)return;const rows=Core.flattenResults(state.analysis.results,state.indicator),h=Object.keys(rows[0]),text='\ufeff'+[h.join(','),...rows.map(r=>h.map(k=>csvEscape(r[k])).join(','))].join('\r\n');downloadBlob(new Blob([text],{type:'text/csv;charset=utf-8'}),fileBase()+'_统计结果.csv')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escSvg(v){return esc(v)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
function persist(){const d={indicator:state.indicator,factorCount:state.factorCount,style:state.style,fields:{experimentName:$('experimentName').value,sampleName:$('sampleName').value,factor1Name:$('factor1Name').value,factor1Type:$('factor1Type').value,factor1Unit:$('factor1Unit').value,factor1Levels:$('factor1Levels').value,factor2Name:$('factor2Name').value,factor2Type:$('factor2Type').value,factor2Unit:$('factor2Unit').value,factor2Levels:$('factor2Levels').value,parallelCount:$('parallelCount').value,measureCount:$('measureCount').value}};localStorage.setItem('freshness-v02',JSON.stringify(d));$('saveStatus').textContent='已保存';clearTimeout(persist.timer);persist.timer=setTimeout(()=>$('saveStatus').textContent='本地自动保存',900)}
function restore(){try{const d=JSON.parse(localStorage.getItem('freshness-v02')||'null');if(!d)return;state.indicator=d.indicator||'pH';state.style=d.style||'nature';for(const[k,v]of Object.entries(d.fields||{}))if($(k))$(k).value=v;setFactorCount(d.factorCount||1);renderStylePresets();updateMetricOptions()}catch{}}
init();
