'use strict';
const Core=window.FreshnessCore;
const $=id=>document.getElementById(id);
const state={indicator:'pH',factorCount:1,design:null,templateRows:[],rawRows:[],analysis:null,currentStep:1,style:'nature',selectedAnalyses:[]};
const PALETTES={
 nature:{name:'Nature-inspired',colors:['#3C5488','#E64B35','#00A087','#4DBBD5','#F39B7F','#8491B4','#91D1C2','#7E6148'],font:'Arial'},
 foodchem:{name:'Food Chemistry-inspired',colors:['#2B1B5A','#F3A44A','#4FA3AA','#F05B61','#6B8E3D','#8B6BB1','#3F78A8','#D38B5D'],font:'Arial'},
 science:{name:'Science-inspired',colors:['#3B4992','#EE0000','#008B45','#631879','#008280','#BB0021','#5F559B','#A20056'],font:'Arial'},
 cell:{name:'Cell-inspired',colors:['#1B9E77','#D95F02','#7570B3','#E7298A','#66A61E','#E6AB02','#A6761D','#666666'],font:'Helvetica'},
 acs:{name:'ACS / color-safe',colors:['#0072B2','#E69F00','#009E73','#D55E00','#CC79A7','#56B4E9','#000000','#F0E442'],font:'Arial'},
 pastel:{name:'Soft editorial',colors:['#4C78A8','#F58518','#54A24B','#E45756','#72B7B2','#B279A2','#FF9DA6','#9D755D'],font:'Arial'},
 mono:{name:'Monochrome',colors:['#111111','#555555','#888888','#BBBBBB','#333333','#777777'],font:'Arial'}
};
const METRIC_LABELS={pH:'pH',L:'L*',a:'a*',b:'b*',C:'C*',h:'h°',DeltaE:'ΔE'};

function init(){bind();renderFactorPreviews();renderStylePresets();restore();updateChartControlState();showHome();}
function bind(){
 $('goHome').onclick=showHome;
 document.querySelectorAll('.metric-card').forEach(b=>b.onclick=()=>selectIndicator(b.dataset.indicator));
 document.querySelectorAll('.factor-count').forEach(b=>b.onclick=()=>setFactorCount(Number(b.dataset.count)));
 ['factor1Name','factor1Type','factor1Unit','factor1Levels','factor2Name','factor2Type','factor2Unit','factor2Levels','parallelCount','measureCount','experimentName','sampleName','outputLanguage','defaultError','missingStrategy'].forEach(id=>$(id).addEventListener('input',()=>{renderFactorPreviews();updateRepeatText();persist()}));
 document.querySelectorAll('.next-button').forEach(b=>b.onclick=()=>goStep(Number(b.dataset.next)));
 document.querySelectorAll('.prev-button').forEach(b=>b.onclick=()=>goStep(Number(b.dataset.prev)));
 document.querySelectorAll('.step').forEach(b=>b.onclick=()=>goStep(Number(b.dataset.step)));
 $('downloadCsv').onclick=downloadTemplateCsv;$('downloadXlsx').onclick=downloadTemplateXlsx;
 $('chooseFile').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>e.target.files[0]&&handleFile(e.target.files[0]);$('loadDemo').onclick=loadDemo;
 const dz=$('dropZone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0]));
 $('runSelectedAnalysis').onclick=runSelectedAnalyses;
 ['chartType','chartMetric','chartLanguage','chartError','figureWidth','exportDpi','showRawPoints','titlePosition','chartTitle','captionNote','xAxisTitle','yAxisTitle','yScaleMode','axisPadding','yMin','yMax','yTickCount','yDecimals','showAxisBreak','axisBreakStyle','axisBreakGap','axisFrame','axisLineWidth','showGrid','fontFamily','titleFontSize','axisFontSize','tickFontSize','legendFontSize','lineWidth','markerSize','barWidth','showLegend','legendPosition','appendLegendUnit','showLegendTitle','legendLabels','seriesEncoding','dashLineCap','errorBarWidth','errorCapWidth','errorBarColorMode','seriesDodge','dodgeDistance','significanceMode','significanceScope','significanceAlpha','significanceOffset','manualLetters','useCustomColors','customColor1','customColor2','customColor3','customColor4','customColor5','customColor6'].forEach(id=>{const el=$(id);if(el)el.addEventListener(['INPUT','TEXTAREA'].includes(el.tagName)?'input':'change',()=>{updateChartControlState();renderChart();persist()})});
 $('resetChartSettings').onclick=resetChartSettings;
 $('exportSvg').onclick=exportSvg;$('exportPng').onclick=exportPng;$('exportCaption').onclick=exportCaption;$('exportResults').onclick=exportResultsCsv;$('finishProject').onclick=()=>{persist();toast('项目已保存在当前设备')};
 $('uiLanguage').onchange=()=>toast('界面双语翻译将在后续版本完成；当前已支持中英文图表输出。');
}
function showHome(){$('homeView').classList.add('active');$('workspaceView').classList.remove('active')}
function selectIndicator(ind){if(!['pH','color'].includes(ind)){toast('该指标将在 pH 与色泽流程稳定后接入');return}state.indicator=ind;$('homeView').classList.remove('active');$('workspaceView').classList.add('active');$('currentIndicatorLabel').textContent=ind==='pH'?'pH 模块':'色泽模块';$('experimentName').value=ind==='pH'?'肉制品 pH 实验':'肉制品色泽实验';updateMetricOptions();goStep(1);persist()}
function setFactorCount(n){state.factorCount=n;document.querySelectorAll('.factor-count').forEach(b=>b.classList.toggle('active',Number(b.dataset.count)===n));$('factor2Card').classList.toggle('hidden',n!==2);renderFactorPreviews();updateRepeatText();persist()}
function safeLevels(id){return Core.parseLevels($(id).value)}
function factorHeader(i,name,unit){return `Factor${i}_${name}${unit?`(${unit})`:''}`}
function getDesign(){const f1={name:$('factor1Name').value.trim()||'因素A',type:$('factor1Type').value,unit:$('factor1Unit').value.trim(),levels:safeLevels('factor1Levels')};f1.header=factorHeader(1,f1.name,f1.unit);const f2={name:$('factor2Name').value.trim()||'因素B',type:$('factor2Type').value,unit:$('factor2Unit').value.trim(),levels:safeLevels('factor2Levels')};f2.header=factorHeader(2,f2.name,f2.unit);return{experimentName:$('experimentName').value.trim(),sampleName:$('sampleName').value.trim(),indicator:state.indicator,factorCount:state.factorCount,factors:[f1,f2],parallelCount:Math.max(2,Number($('parallelCount').value)||3),measureCount:Math.max(1,Number($('measureCount').value)||1),outputLanguage:$('outputLanguage').value,defaultError:$('defaultError').value,missingStrategy:$('missingStrategy').value}}
function renderFactorPreviews(){for(const i of [1,2]){const box=$(`factor${i}Preview`),levels=safeLevels(`factor${i}Levels`);box.innerHTML=levels.slice(0,16).map(x=>`<span>${esc(x)}</span>`).join('')+(levels.length>16?`<span>+${levels.length-16}</span>`:'')}const d=getDesign();$('designSummaryBadge').textContent=d.factorCount===1?'单因素设计':'双因素析因设计';}
function updateRepeatText(){const p=Math.max(2,Number($('parallelCount').value)||3),m=Math.max(1,Number($('measureCount').value)||1);$('repeatExplanation').textContent=`每个条件 ${p} 个独立平行样品，每个样品测 ${m} 次；技术重复先求样品均值，统计 n=${p}。`}
function validateDesign(d){const e=[];if(!d.experimentName)e.push('请填写实验名称。');if(!d.factors[0].levels.length)e.push('因素A至少需要1个水平。');if(d.factorCount===2&&!d.factors[1].levels.length)e.push('因素B至少需要1个水平。');if(new Set(d.factors[0].levels).size!==d.factors[0].levels.length)e.push('因素A水平存在重复。');if(d.factorCount===2&&new Set(d.factors[1].levels).size!==d.factors[1].levels.length)e.push('因素B水平存在重复。');return e}
function goStep(n){if(n>=2){const d=getDesign(),e=validateDesign(d);if(e.length){toast(e[0]);return}state.design=d;buildTemplate();renderAnalysisCards();updateMetricOptions()}state.currentStep=n;document.querySelectorAll('.wizard-page').forEach(p=>p.classList.toggle('active',Number(p.dataset.page)===n));document.querySelectorAll('.step').forEach(s=>{const k=Number(s.dataset.step);s.classList.toggle('active',k===n);s.classList.toggle('done',k<n)});if(n===5){updateChartControlState();renderChart();}window.scrollTo({top:72,behavior:'smooth'});persist()}
function combinations(d){const out=[];for(const a of d.factors[0].levels){if(d.factorCount===1)out.push([a,'']);else for(const b of d.factors[1].levels)out.push([a,b])}return out}
function metricHeaders(){return state.indicator==='pH'?['pH']:['L*','a*','b*']}
function factorDisplayHeader(f){return `${f.name}${f.unit?`(${f.unit})`:''}`}
function toUserTemplateRows(){const d=state.design||getDesign();return state.templateRows.map(r=>{const out={'样品编号':r.SampleID};out[factorDisplayHeader(d.factors[0])]=r[d.factors[0].header];if(d.factorCount===2)out[factorDisplayHeader(d.factors[1])]=r[d.factors[1].header];out['平行样品编号']=r.ParallelSample;out['测量重复编号']=r.MeasureReplicate;for(const h of metricHeaders())out[h]=r[h];out['是否纳入']=r.Include;out['备注']=r.Notes;return out})}
function buildTemplate(){const d=state.design||getDesign(),rows=[];for(const [a,b] of combinations(d))for(let p=1;p<=d.parallelCount;p++)for(let m=1;m<=d.measureCount;m++){const r={SampleID:`${String(a).replace(/\s/g,'')}${d.factorCount===2?'-'+String(b).replace(/\s/g,''):''}-S${p}${d.measureCount>1?'-M'+m:''}`};r[d.factors[0].header]=a;if(d.factorCount===2)r[d.factors[1].header]=b;r.ParallelSample=p;r.MeasureReplicate=m;for(const h of metricHeaders())r[h]='';r.Include='是';r.Notes='';rows.push(r)}state.templateRows=rows;$('templateRowBadge').textContent=`预计 ${rows.length} 行`;$('templateSummary').innerHTML=[`指标：${state.indicator==='pH'?'pH':'色泽 L* a* b*'}`,`${d.factorCount===1?'单因素':'双因素'}`,`${combinations(d).length} 个条件组合`,`${d.parallelCount} 平行 × ${d.measureCount} 次测量`].map(x=>`<span class="summary-pill">${esc(x)}</span>`).join('');renderTable($('templatePreviewTable'),toUserTemplateRows().slice(0,12));}
function renderTable(table,rows){if(!rows.length){table.innerHTML='<tbody><tr><td class="empty-cell">无数据</td></tr></tbody>';return}const heads=Object.keys(rows[0]);table.innerHTML=`<thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${heads.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody>`}
function designSheetRows(d){return[['项目','值'],['实验名称',d.experimentName],['样品名称',d.sampleName],['指标',d.indicator],['因素数量',d.factorCount],['因素A名称',d.factors[0].name],['因素A类型',d.factors[0].type],['因素A单位',d.factors[0].unit],['因素A水平',d.factors[0].levels.join(', ')],['因素B名称',d.factorCount===2?d.factors[1].name:''],['因素B类型',d.factorCount===2?d.factors[1].type:''],['因素B单位',d.factorCount===2?d.factors[1].unit:''],['因素B水平',d.factorCount===2?d.factors[1].levels.join(', '):''],['独立平行数',d.parallelCount],['每样品测量次数',d.measureCount],['说明','本页由软件自动生成，请勿修改。若实验设计变化，请返回软件重新生成模板。']]}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadTemplateCsv(){buildTemplate();const rows=toUserTemplateRows(),heads=Object.keys(rows[0]),text='\ufeff'+[heads.join(','),...rows.map(r=>heads.map(h=>csvEscape(r[h])).join(','))].join('\r\n');downloadBlob(new Blob([text],{type:'text/csv;charset=utf-8'}),fileBase()+'_数据填写模板.csv');toast('CSV 数据填写模板已生成')}
function downloadTemplateXlsx(){buildTemplate();if(!window.XLSX){toast('Excel组件未加载，请先下载 CSV；最终桌面版会内置组件。');return}const rows=toUserTemplateRows(),wb=XLSX.utils.book_new(),dataWs=XLSX.utils.json_to_sheet(rows),designWs=XLSX.utils.aoa_to_sheet(designSheetRows(state.design)),fillable=state.indicator==='pH'?'pH':'L*、a*、b*',guide=XLSX.utils.aoa_to_sheet([['食品实验数据分析平台——模板填写说明'],['请直接打开第一个工作表“数据填写”。'],[`本次只需填写：${fillable} 数据列；“备注”可选填。`],['样品编号、因素水平、平行样品编号和测量重复编号均已自动生成，请勿修改。'],['每一行代表一个独立样品的一次仪器测量。'],['不要填写平均值、标准差或“平均值±标准差”，只填写单个原始数值。'],['“是否纳入”默认填“是”；排除数据时改为“否”，并在备注中说明原因。'],['如需更改因素、水平、组数或重复数，请返回软件重新生成模板，不要直接改项目配置。']]);dataWs['!cols']=Object.keys(rows[0]).map(h=>({wch:h==='备注'?28:h==='样品编号'?22:h.includes('编号')?14:Math.max(12,Math.min(22,String(h).length*2+4))}));dataWs['!autofilter']={ref:dataWs['!ref']};designWs['!cols']=[{wch:20},{wch:48}];guide['!cols']=[{wch:92}];XLSX.utils.book_append_sheet(wb,dataWs,'数据填写');XLSX.utils.book_append_sheet(wb,designWs,'项目配置（勿改）');XLSX.utils.book_append_sheet(wb,guide,'填写说明');XLSX.writeFile(wb,fileBase()+'_可填写模板.xlsx');toast(`Excel 模板已生成：打开“数据填写”，只填 ${fillable} 列`)}
function fileBase(){return(state.design?.experimentName||'实验').replace(/[\\/:*?"<>|]/g,'_')+'_'+(state.indicator==='pH'?'pH':'色泽')}
async function handleFile(file){try{let rows;if(file.name.toLowerCase().endsWith('.csv'))rows=parseCsv(await file.text());else{if(!window.XLSX)throw new Error('Excel组件未加载，请使用 CSV 或联网重新打开。');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),name=wb.SheetNames.includes('数据填写')?'数据填写':wb.SheetNames.includes('原始数据')?'原始数据':wb.SheetNames[0];rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:true})}processImported(rows,file.name)}catch(e){showValidation([e.message],[]);$('importBadge').textContent='导入失败';toast(e.message)}}
function mapImportedRows(rows){const d=state.design||getDesign();return rows.map(r=>{const keys=Object.keys(r),findFactor=(f,index)=>keys.find(k=>k===`Factor${index}`||k.startsWith(`Factor${index}_`)||k===f.header||k===factorDisplayHeader(f)||k===f.name||k.startsWith(`${f.name}(`)),f1k=findFactor(d.factors[0],1)||d.factors[0].header,f2k=findFactor(d.factors[1],2)||d.factors[1].header;return{...r,Factor1:r[f1k]??'',Factor2:d.factorCount===2?(r[f2k]??''):'',ParallelSample:r.ParallelSample??r['平行样品']??r['平行样品编号']??r['独立平行编号'],MeasureReplicate:r.MeasureReplicate??r['测量重复']??r['测量重复编号']??r['测量编号']??1,pH:r.pH??r['pH值']??r['pH（请填写）'],L:r.L??r['L*'],a:r.a??r['a*'],b:r.b??r['b*'],Include:r.Include??r['纳入']??r['是否纳入']??'是',Notes:r.Notes??r['备注']??''}})}
function processImported(rows,name){state.rawRows=mapImportedRows(rows);const normalized=Core.normalizeRows(state.rawRows,state.design,state.indicator);state.analysis=Core.analyze(normalized,state.design,state.indicator);showValidation(state.analysis.validation.errors,state.analysis.validation.warnings);$('importBadge').textContent=`${name} · ${rows.length}行`;renderRawPreview(normalized);const ok=state.analysis.validation.valid;$('toAnalysis').disabled=!ok;$('exportSvg').disabled=!ok;$('exportPng').disabled=!ok;$('exportResults').disabled=!ok;if(ok){renderAnalysisCards();renderChart();toast('数据校验完成')}persist()}
function showValidation(errors,warnings){const box=$('validationBox');box.className='validation-box';let html='';if(!errors.length&&!warnings.length)html='<div class="issue success">✓ 数据结构完整，可以分析。</div>';html+=errors.map(x=>`<div class="issue error">${esc(x)}</div>`).join('');html+=warnings.map(x=>`<div class="issue warning">${esc(x)}</div>`).join('');box.innerHTML=html||'<div class="issue success">✓ 校验完成。</div>'}
function renderRawPreview(rows){const display=rows.slice(0,80).map(r=>state.indicator==='pH'?{Factor1:r.Factor1,Factor2:r.Factor2,ParallelSample:r.ParallelSample,MeasureReplicate:r.MeasureReplicate,pH:r.pH}:{Factor1:r.Factor1,Factor2:r.Factor2,ParallelSample:r.ParallelSample,MeasureReplicate:r.MeasureReplicate,'L*':r.L,'a*':r.a,'b*':r.b});renderTable($('rawPreview'),display)}
function loadDemo(){state.design=getDesign();const rows=[],noise=[-.03,.01,.02];for(const [ai,a] of state.design.factors[0].levels.entries()){const bLevels=state.design.factorCount===2?state.design.factors[1].levels:[''];for(const [bi,b] of bLevels.entries())for(let p=1;p<=state.design.parallelCount;p++)for(let m=1;m<=state.design.measureCount;m++){const n=noise[(p+m-2)%noise.length];if(state.indicator==='pH')rows.push({Factor1:a,Factor2:b,ParallelSample:p,MeasureReplicate:m,pH:5.58+ai*.04+bi*.08+n,Include:'是'});else rows.push({Factor1:a,Factor2:b,ParallelSample:p,MeasureReplicate:m,L:52-ai*.45+bi*.3+n*3,a:13-ai*.5-bi*.3+n*2,b:8+ai*.25+bi*.2+n,Include:'是'})}}processImported(rows,'内置演示数据')}
function parseCsv(text){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const delim=lines[0].includes('\t')?'\t':',';const split=line=>{let a=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&q){v+='"';i++}else if(c==='"')q=!q;else if(c===delim&&!q){a.push(v);v=''}else v+=c}a.push(v);return a};const h=split(lines[0]);return lines.slice(1).map(l=>Object.fromEntries(h.map((x,i)=>[x,split(l)[i]??''])))}
function updateMetricOptions(){const opts=state.indicator==='pH'?[['pH','pH']]:[['L','L*'],['a','a*'],['b','b*'],['C','C*'],['h','h°'],['DeltaE','ΔE']];$('chartMetric').innerHTML=opts.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}
function renderAnalysisCards(){const d=state.design||getDesign(),numericA=d.factors[0].type==='numeric';const methods=[
 {id:'descriptive',title:'描述统计与论文结果表',desc:'Mean、SD、SE、95% CI、CV、范围与样品级数据。',tags:['基础','已实现'],rec:true,impl:true},
 {id:'oneway',title:'单因素方差分析',desc:'比较一个因素多个水平；输出 F、P 和 η²。',tags:['One-way ANOVA','已实现'],rec:d.factorCount===1,impl:d.factorCount===1},
 {id:'twoway',title:'双因素方差分析与交互作用',desc:'分别检验因素A、因素B和 A×B 交互作用。',tags:['Two-way ANOVA','已实现'],rec:d.factorCount===2,impl:d.factorCount===2},
 {id:'trend',title:'剂量/时间趋势分析',desc:'数值型因素的线性趋势、斜率、R²和趋势显著性。',tags:['Regression','已实现'],rec:numericA,impl:numericA},
 {id:'posthoc',title:'多重比较与显著性字母',desc:'Tukey、Duncan、LSD、Bonferroni；按同一时间比较组别或同组比较水平。',tags:['Post hoc','下一阶段'],rec:true,impl:false},
 {id:'assumption',title:'正态性与方差齐性',desc:'Shapiro–Wilk、Levene/Brown–Forsythe，并据此提示参数或非参数检验。',tags:['前提检验','下一阶段'],rec:true,impl:false},
 {id:'nonparametric',title:'非参数检验',desc:'Kruskal–Wallis、Mann–Whitney、Dunn 多重比较。',tags:['稳健分析','下一阶段'],rec:false,impl:false},
 {id:'outlier',title:'异常值与重复性诊断',desc:'标记可疑点、组内CV和技术重复差异；仅提示，不自动删除。',tags:['质量控制','下一阶段'],rec:true,impl:false},
 {id:'effect',title:'效应量与置信区间',desc:'η²、偏η²、组间差值及置信区间，避免只报告P值。',tags:['论文增强','部分实现'],rec:true,impl:true}
 ];$('analysisCards').innerHTML=methods.map(m=>`<label class="analysis-card ${m.rec?'recommended':''}"><input type="checkbox" value="${m.id}" ${m.rec?'checked':''}><h3>${m.title}</h3><p>${m.desc}</p>${m.tags.map(t=>`<span class="method-tag">${t}</span>`).join('')}</label>`).join('');$('analysisRecommendationBadge').textContent=d.factorCount===1?(numericA?'单因素 + 趋势':'单因素组间比较'):'双因素 + 交互作用'}
function runSelectedAnalyses(){if(!state.analysis?.results.length){toast('请先导入有效数据');return}const ids=[...document.querySelectorAll('#analysisCards input:checked')].map(x=>x.value),metric=$('chartMetric').value||'pH';let html='';if(ids.includes('descriptive'))html+=renderDescriptive(metric);if(ids.includes('oneway')&&state.design.factorCount===1){const a=Core.oneWayAnova(state.analysis.samples,metric);html+=anovaHtml('单因素 ANOVA',a)}if(ids.includes('twoway')&&state.design.factorCount===2){const a=Core.twoWayAnova(state.analysis.samples,metric,state.design);html+=twoWayHtml(a)}if(ids.includes('trend')&&state.design.factors[0].type==='numeric'){const r=Core.linearRegression(state.analysis.samples,metric);html+=trendHtml(r)}const pending=ids.filter(x=>['posthoc','assumption','nonparametric','outlier'].includes(x));if(pending.length)html+=`<div class="result-block"><h4>已选择但尚未接入计算引擎</h4><div class="issue warning">${pending.join('、')} 已进入开发清单；当前版本不会伪造这些结果。</div></div>`;$('analysisOutput').className='analysis-output';$('analysisOutput').innerHTML=html||'未选择可运行分析';}
function fmt(v,d=4){return v==null||!Number.isFinite(v)?'—':Number(v).toFixed(d)}function pFmt(p){return p==null?'—':p<.001?'P < 0.001':`P = ${p.toFixed(3)}`}
function renderDescriptive(metric){const items=state.analysis.results.map(r=>{const s=r[metric];return`<div class="result-item"><b>${esc(r.Factor1)}${r.Factor2?' × '+esc(r.Factor2):''}</b><span>${fmt(s?.mean,3)} ± ${fmt(s?.sd,3)} · n=${s?.n??0}</span></div>`}).join('');return`<div class="result-block"><h4>${METRIC_LABELS[metric]||metric} 描述统计（Mean ± SD）</h4><div class="result-list">${items}</div></div>`}
function anovaHtml(title,a){return`<div class="result-block"><h4>${title}</h4><div class="result-list"><div class="result-item"><b>F(${a.dfBetween}, ${a.dfWithin})</b><span>${fmt(a.F,3)}</span></div><div class="result-item"><b>显著性</b><span>${pFmt(a.p)}</span></div><div class="result-item"><b>η²</b><span>${fmt(a.eta2,3)}</span></div><div class="result-item"><b>样本数</b><span>N=${a.N}</span></div></div></div>`}
function twoWayHtml(a){if(a.error&&typeof a.error==='string')return`<div class="issue warning">${a.error}</div>`;const row=(name,x)=>`<div class="result-item"><b>${name}</b><span>F=${fmt(x.F,3)} · ${pFmt(x.p)} · partial η²=${fmt(x.partialEta2,3)}</span></div>`;return`<div class="result-block"><h4>双因素 ANOVA</h4><div class="result-list">${row(state.design.factors[0].name,a.A)}${row(state.design.factors[1].name,a.B)}${row('交互作用',a.interaction)}<div class="result-item"><b>单元重复</b><span>n=${a.nPerCell}</span></div></div></div>`}
function trendHtml(r){if(r.error)return`<div class="issue warning">${r.error}</div>`;return`<div class="result-block"><h4>线性趋势</h4><div class="result-list"><div class="result-item"><b>回归方程</b><span>y=${fmt(r.intercept,3)} + ${fmt(r.slope,4)}x</span></div><div class="result-item"><b>R²</b><span>${fmt(r.r2,3)}</span></div><div class="result-item"><b>趋势检验</b><span>${pFmt(r.p)}</span></div><div class="result-item"><b>观测数</b><span>N=${r.n}</span></div></div></div>`}
function renderStylePresets(){$('stylePresets').innerHTML=Object.entries(PALETTES).map(([id,p])=>`<button type="button" class="style-preset ${id===state.style?'active':''}" data-style="${id}"><b>${p.name}</b><span class="swatches">${p.colors.slice(0,6).map(c=>`<span style="background:${c}"></span>`).join('')}</span></button>`).join('');document.querySelectorAll('.style-preset').forEach(b=>b.onclick=()=>{state.style=b.dataset.style;if($('fontFamily'))$('fontFamily').value=PALETTES[state.style].font;renderStylePresets();renderChart();persist()})}
function renderChart(){
 const box=$('chartCanvas'),warning=$('chartWarning'),captionBox=$('captionPreview');
 if(!state.analysis?.results.length){box.innerHTML='<div class="empty-chart">导入数据后生成图表</div>';if(warning)warning.classList.add('hidden');if(captionBox)captionBox.innerHTML='<b>图注预览</b><p>导入数据后自动生成。</p>';return}
 const metric=$('chartMetric').value||'pH',d=state.design,pal=PALETTES[state.style]||PALETTES.foodchem;
 const colors=$('useCustomColors').checked?[1,2,3,4,5,6].map(i=>$(`customColor${i}`).value):pal.colors;
 const lang=$('chartLanguage').value,error=$('chartError').value,type=resolveChartType();
 const results=state.analysis.results.filter(r=>r[metric]?.mean!=null),seriesLevels=d.factorCount===2?d.factors[1].levels:[''],multiSeries=seriesLevels.length>1;
 const showLegend=$('showLegend').checked&&multiSeries,legendPosition=$('legendPosition').value,titlePosition=$('titlePosition').value,captionNote=$('captionNote').value.trim();
 const font=$('fontFamily').value||pal.font||'Arial',titleSize=numInput('titleFontSize',12),axisSize=numInput('axisFontSize',13),tickSize=numInput('tickFontSize',11),legendSize=numInput('legendFontSize',10);
 const lineWidth=numInput('lineWidth',1.8),markerSize=numInput('markerSize',4.2),barRatio=numInput('barWidth',.62),errorBarWidth=numInput('errorBarWidth',1.2),errorCapWidth=numInput('errorCapWidth',18),axisLineWidth=numInput('axisLineWidth',1.2),breakGap=Math.max(22,numInput('axisBreakGap',30));
 const encoding=$('seriesEncoding').value,dashCap=$('dashLineCap').value||'round',dodgeEnabled=$('seriesDodge').value==='auto'&&multiSeries&&type!=='bar',dodgeDistance=dodgeEnabled?numInput('dodgeDistance',5):0;
 const sigMode=$('significanceMode').value,effectiveSigMode=sigMode==='auto'?(type==='bar'?'lsd':'none'):sigMode,sigOffset=numInput('significanceOffset',14),sigLetters=getSignificanceMap(metric,effectiveSigMode),hasSig=Object.keys(sigLetters).some(k=>sigLetters[k]);
 const legendTop=showLegend&&legendPosition.startsWith('top-'),legendBottom=showLegend&&legendPosition.startsWith('bottom-'),titleTop=titlePosition==='top',titleBottom=titlePosition==='bottom';
 const topExtra=(titleTop?28:0)+(legendTop?34:0),bottomExtra=(legendBottom?34:0)+(titleBottom?(captionNote?58:38):0);
 const W=legendPosition==='right'&&showLegend?1040:960,H=500+topExtra+bottomExtra,M={l:82,r:(legendPosition==='right'&&showLegend?180:34),t:32+topExtra,b:62+bottomExtra};
 const baseY=H-M.b,iw=W-M.l-M.r;
 const vals=results.flatMap(r=>{const s=r[metric],e=getErr(s,error)||0;return[s.mean-e,s.mean+e]}).filter(Number.isFinite);let dataMin=Math.min(...vals),dataMax=Math.max(...vals);
 if(!Number.isFinite(dataMin)||!Number.isFinite(dataMax))return;if(dataMin===dataMax){const delta=Math.abs(dataMin||1)*.05||1;dataMin-=delta;dataMax+=delta}
 if(hasSig){const span=Math.max(dataMax-dataMin,.1);dataMax+=span*.05}
 const targetTicks=Math.max(3,Number($('yTickCount').value)||6),scaleMode=$('yScaleMode').value,padPct=Math.max(0,numInput('axisPadding',6))/100;let ymin,ymax,step,ticks,scaleNotice='';
 if(scaleMode==='custom'&&Number.isFinite(Number($('yMin').value))&&Number.isFinite(Number($('yMax').value))&&Number($('yMax').value)>Number($('yMin').value)){ymin=Number($('yMin').value);ymax=Number($('yMax').value);if(ymin>dataMin||ymax<dataMax){const span=Math.max(dataMax-dataMin,Math.abs(dataMax||1)*.05,.1);ymin=Math.min(ymin,dataMin-span*padPct);ymax=Math.max(ymax,dataMax+span*padPct);scaleNotice='自定义纵轴范围无法容纳全部误差棒或显著性字母，已自动扩展。'}step=(ymax-ymin)/(targetTicks-1);ticks=Array.from({length:targetTicks},(_,i)=>ymin+i*step)}else{const includeZero=scaleMode==='zero'||(scaleMode==='auto'&&type==='bar');const s=smartScale(dataMin,dataMax,targetTicks,includeZero,padPct);ymin=s.min;ymax=s.max;step=s.step;ticks=s.ticks}
 if(!(ymax>ymin)){ymin=dataMin-1;ymax=dataMax+1;step=(ymax-ymin)/(targetTicks-1);ticks=Array.from({length:targetTicks},(_,i)=>ymin+i*step)}
 const axisBreakEnabled=$('showAxisBreak').checked&&ymin>0&&scaleMode!=='zero',plotBottom=axisBreakEnabled?baseY-breakGap:baseY,ih=plotBottom-M.t,y=v=>M.t+ih-(v-ymin)/(ymax-ymin)*ih;
 const levels=d.factors[0].levels,numeric=d.factors[0].type==='numeric',nums=levels.map(Number),xmin=Math.min(...nums),xmax=Math.max(...nums),xCat=v=>M.l+(levels.indexOf(String(v))+.5)*iw/levels.length,xNum=v=>levels.length===1?M.l+iw/2:M.l+(Number(v)-xmin)/(xmax-xmin||1)*iw,xBase=v=>numeric&&['line','scatter','interaction'].includes(type)?xNum(v):xCat(v);
 const errorOffset=si=>dodgeEnabled?(si-(seriesLevels.length-1)/2)*dodgeDistance:0,autoTitle=lang==='en'?`${METRIC_LABELS[metric]||metric} response`:`${METRIC_LABELS[metric]||metric} 变化`,title=$('chartTitle').value.trim()||autoTitle,xlabel=$('xAxisTitle').value.trim()||axisLabel(d.factors[0],lang),ylabel=$('yAxisTitle').value.trim()||(METRIC_LABELS[metric]||metric),decimals=resolveDecimals(step,$('yDecimals').value),figWidth=Number($('figureWidth').value)||120,figHeight=figWidth*H/W,frame=$('axisFrame').value,breakStyle=$('axisBreakStyle').value;
 let svg=`<svg id="paperChart" xmlns="http://www.w3.org/2000/svg" width="${figWidth}mm" height="${figHeight.toFixed(2)}mm" viewBox="0 0 ${W} ${H}" style="font-family:${escSvg(font)},Arial,sans-serif;background:white"><rect width="100%" height="100%" fill="white"/>`;
 for(const v of ticks){const yy=y(v);if($('showGrid').checked)svg+=`<line x1="${M.l}" y1="${yy}" x2="${W-M.r}" y2="${yy}" stroke="#e9e9e9" stroke-width=".9"/>`;if(frame!=='none')svg+=`<line x1="${M.l-5}" y1="${yy}" x2="${M.l}" y2="${yy}" stroke="#202020" stroke-width="${axisLineWidth}"/>`;svg+=`<text x="${M.l-10}" y="${yy+tickSize*.36}" text-anchor="end" font-size="${tickSize}" fill="#202020">${formatTick(v,decimals)}</text>`}
 svg+=frameSvg(frame,M.l,W-M.r,M.t,plotBottom,baseY,axisLineWidth,axisBreakEnabled,breakStyle);
 levels.forEach(l=>{const xx=xBase(l);if(frame!=='none')svg+=`<line x1="${xx}" y1="${baseY}" x2="${xx}" y2="${baseY+5}" stroke="#202020" stroke-width="${axisLineWidth}"/>`;svg+=`<text x="${xx}" y="${baseY+22}" text-anchor="middle" font-size="${tickSize}" fill="#202020">${escSvg(l)}</text>`});
 if(titleTop)svg+=`<text data-edit-target="chartTitle" class="editable-chart-text" x="${W/2}" y="22" text-anchor="middle" font-size="${titleSize}" font-weight="600" fill="#111">${escSvg(title)}</text>`;
 svg+=`<text data-edit-target="xAxisTitle" class="editable-chart-text" x="${M.l+iw/2}" y="${baseY+45}" text-anchor="middle" font-size="${axisSize}" fill="#111">${escSvg(xlabel)}</text><text data-edit-target="yAxisTitle" class="editable-chart-text" x="22" y="${M.t+ih/2}" text-anchor="middle" transform="rotate(-90 22 ${M.t+ih/2})" font-size="${axisSize}" fill="#111">${escSvg(ylabel)}</text>`;
 let barLayer='',errorLayer='',lineLayer='',pointLayer='',rawLayer='',sigLayer='';
 if(type==='bar'){
   const band=iw/levels.length,bw=Math.max(8,Math.min(68,band/Math.max(1,seriesLevels.length)*barRatio)),zeroBase=(ymin<=0&&ymax>=0)?y(0):plotBottom;
   seriesLevels.forEach((sl,si)=>results.filter(r=>String(r.Factor2||'')===String(sl||'')).forEach(r=>{const style=seriesStyle(si,encoding,colors),xx=xCat(r.Factor1)+(si-(seriesLevels.length-1)/2)*bw*1.12,yy=y(r[metric].mean),err=getErr(r[metric],error);barLayer+=`<rect x="${xx-bw/2}" y="${Math.min(yy,zeroBase)}" width="${bw}" height="${Math.abs(zeroBase-yy)}" fill="${style.color}" fill-opacity=".88" stroke="${style.color}" stroke-width=".8"/>`;errorLayer+=errorBarSvg(xx,r[metric].mean,err,y,{capWidth:errorCapWidth,lineWidth:errorBarWidth,color:errorColor(style.color)});if($('showRawPoints').checked)sampleValuesFor(r,metric).forEach((v,j,arr)=>rawLayer+=`<circle cx="${xx+(j-(arr.length-1)/2)*6}" cy="${y(v)}" r="3" fill="#fff" stroke="#222" stroke-width="1"/>`);const letter=sigLetters[resultKey(r)];if(letter)sigLayer+=`<text x="${xx}" y="${Math.max(M.t+11,y(r[metric].mean+(err||0))-sigOffset)}" text-anchor="middle" font-size="${Math.max(9,tickSize)}" font-weight="600">${escSvg(letter)}</text>`}))
 }else{
   seriesLevels.forEach((sl,si)=>{const style=seriesStyle(si,encoding,colors),rr=results.filter(r=>String(r.Factor2||'')===String(sl||'')).sort((a,b)=>levels.indexOf(String(a.Factor1))-levels.indexOf(String(b.Factor1))),pts=rr.map(r=>`${xBase(r.Factor1)},${y(r[metric].mean)}`).join(' ');if(type!=='scatter')lineLayer+=`<polyline fill="none" stroke="${style.color}" stroke-width="${lineWidth}" stroke-dasharray="${style.dash}" stroke-linejoin="miter" stroke-linecap="${dashCap}" points="${pts}"/>`;rr.forEach(r=>{const xx=xBase(r.Factor1),yy=y(r[metric].mean),errX=xx+errorOffset(si),err=getErr(r[metric],error);errorLayer+=errorBarSvg(errX,r[metric].mean,err,y,{capWidth:errorCapWidth,lineWidth:errorBarWidth,color:errorColor(style.color)});pointLayer+=pointSvg(xx,yy,style.color,style.shape,markerSize);if($('showRawPoints').checked)sampleValuesFor(r,metric).forEach((v,j,arr)=>rawLayer+=`<circle cx="${errX+(j-(arr.length-1)/2)*4.5}" cy="${y(v)}" r="2.1" fill="#fff" stroke="${style.color}" stroke-width="1" opacity=".8"/>`);const letter=sigLetters[resultKey(r)];if(letter)sigLayer+=`<text x="${errX}" y="${Math.max(M.t+11,y(r[metric].mean+(err||0))-sigOffset)}" text-anchor="middle" font-size="${Math.max(9,tickSize)}" font-weight="600">${escSvg(letter)}</text>`})})
 }
 svg+=barLayer+errorLayer+lineLayer+pointLayer+rawLayer+sigLayer;
 if(showLegend)svg+=legendSvg(seriesLevels,colors,d,legendPosition,W,H,M,legendSize,lineWidth,markerSize,encoding,dashCap,baseY,titleTop);
 if(titleBottom){const legendShift=legendBottom?30:0,captionY=baseY+76+legendShift;svg+=captionSvg(title,captionNote,W,captionY,titleSize,Math.max(9,titleSize-1))}
 svg+='</svg>';box.innerHTML=svg;bindChartTextEditing();
 const alpha=Number($('significanceAlpha').value)||.05,sigSentence=effectiveSigMode==='lsd'&&hasSig?(lang==='en'?`Different lowercase letters indicate significant differences (Fisher's LSD, P < ${alpha}).`:`不同小写字母表示差异显著（Fisher LSD，P < ${alpha}）。`):'',defaultNote=captionNote||(lang==='en'?`Data are expressed as mean ± ${error==='se'?'SE':error==='ci'?'95% CI':'SD'} (n = ${d.parallelCount}).`:`数据表示为平均值 ± ${error==='se'?'SE':error==='ci'?'95% CI':'SD'}（n = ${d.parallelCount}）。`),captionText=[title,defaultNote,sigSentence].filter(Boolean).join(' ');
 if(captionBox)captionBox.innerHTML=`<b data-edit-target="chartTitle">图注预览</b><p>${esc(captionText)}</p>`;
 const notices=[];if(scaleNotice)notices.push(scaleNotice);if(axisBreakEnabled)notices.push('已启用真实断轴：纵轴在断裂区间内不连续。');if(ymin>0&&!axisBreakEnabled&&type==='bar')notices.push('柱状图使用非零起点会夸大差异；建议从 0 开始，或明确启用断轴。');if(effectiveSigMode==='lsd'&&hasSig)notices.push('显著性字母由 Fisher LSD 自动生成；请确认该方法适合你的实验设计。');
 if(warning){warning.classList.toggle('hidden',!notices.length);warning.textContent=notices.join(' ')}
 $('chartTitleText').textContent=titlePosition==='none'?`${title}（图注外置）`:title;$('chartStyleText').textContent=`v0.2.5 · ${pal.name} · ${encodingLabel(encoding)} · ${figWidth} mm · ${$('exportDpi').value} dpi`;
 $('exportSvg').disabled=false;$('exportPng').disabled=false;$('exportCaption').disabled=false;$('exportResults').disabled=false;
}
function resolveChartType(){const v=$('chartType').value;if(v!=='auto')return v;const d=state.design;if(d.factorCount===2)return d.factors[0].type==='numeric'?'interaction':'bar';return d.factors[0].type==='numeric'?'line':'bar'}
function getErr(s,e){return e==='sd'?s.sd:e==='se'?s.se:e==='ci'?s.ci:0}
function errorColor(seriesColor){return $('errorBarColorMode').value==='series'?seriesColor:'#222222'}
function errorBarSvg(x,meanValue,e,yfn,opt={}){if(!e||!Number.isFinite(e)||!Number.isFinite(meanValue))return'';const top=yfn(meanValue+e),bot=yfn(meanValue-e),cap=Math.max(3,(opt.capWidth||18)/2),stroke=opt.color||'#222',sw=opt.lineWidth||1.2;return`<g class="error-bar"><line x1="${x}" y1="${top}" x2="${x}" y2="${bot}" stroke="${stroke}" stroke-width="${sw}"/><line x1="${x-cap}" y1="${top}" x2="${x+cap}" y2="${top}" stroke="${stroke}" stroke-width="${sw}"/><line x1="${x-cap}" y1="${bot}" x2="${x+cap}" y2="${bot}" stroke="${stroke}" stroke-width="${sw}"/></g>`}
function pointSvg(x,y,c,shape,size=4.2){if(shape===1)return`<rect x="${x-size}" y="${y-size}" width="${size*2}" height="${size*2}" fill="${c}"/>`;if(shape===2)return`<path d="M${x},${y-size-1} L${x+size+1},${y+size} L${x-size-1},${y+size} Z" fill="${c}"/>`;if(shape===3)return`<path d="M${x},${y-size-1} L${x+size+1},${y} L${x},${y+size+1} L${x-size-1},${y} Z" fill="${c}"/>`;if(shape===4)return`<path d="M${x-size},${y-size} L${x+size},${y+size} M${x+size},${y-size} L${x-size},${y+size}" stroke="${c}" stroke-width="2"/>`;return`<circle cx="${x}" cy="${y}" r="${size}" fill="${c}"/>`}
function axisLabel(f,lang){const unit=f.unit?` (${f.unit})`:'';if(lang==='en'){const dict={'储藏时间':'Storage time','贮藏时间':'Storage time','添加量':'Addition level','温度':'Temperature','包装方式':'Packaging treatment'};return(dict[f.name]||f.name)+unit}return f.name+unit}
function numInput(id,fallback){const n=Number($(id)?.value);return Number.isFinite(n)?n:fallback}
function niceNumber(x,round){const exp=Math.floor(Math.log10(Math.abs(x)||1)),f=x/10**exp,n=round?(f<1.5?1:f<3?2:f<7?5:10):(f<=1?1:f<=2?2:f<=5?5:10);return n*10**exp}
function smartScale(min,max,targetTicks,includeZero,padPct){const rawSpan=Math.max(max-min,Math.abs(max||1)*.04,.05),pmin=includeZero&&min>=0?0:min-rawSpan*padPct,pmax=includeZero&&max<=0?0:max+rawSpan*padPct,step=niceNumber((pmax-pmin)/Math.max(2,targetTicks-1),true),niceMin=includeZero&&min>=0?0:Math.floor(pmin/step)*step,niceMax=includeZero&&max<=0?0:Math.ceil(pmax/step)*step,ticks=[];for(let v=niceMin,i=0;v<=niceMax+step*.25&&i<30;v+=step,i++)ticks.push(Number(v.toPrecision(12)));return{min:niceMin,max:niceMax,step,ticks}}
function resolveDecimals(step,value){if(value!=='auto')return Number(value);if(!Number.isFinite(step)||step===0)return 2;return Math.max(0,Math.min(4,-Math.floor(Math.log10(Math.abs(step)))+(Math.abs(step/10**Math.floor(Math.log10(Math.abs(step))))<2?1:0)))}
function formatTick(v,d){const n=Math.abs(v)<10**(-d)/2?0:v;return Number(n).toFixed(d)}
function lineDash(i){return['','9 5','2.5 4','11 4 2 4','5 4'][i%5]}
function seriesStyle(i,encoding,colors){const base=colors[0]||'#202020';if(encoding==='line')return{color:base,dash:lineDash(i),shape:0};if(encoding==='marker')return{color:base,dash:'',shape:i%5};if(encoding==='color-line')return{color:colors[i%colors.length]||base,dash:lineDash(i),shape:0};if(encoding==='color-marker')return{color:colors[i%colors.length]||base,dash:'',shape:i%5};return{color:colors[i%colors.length]||base,dash:'',shape:0}}
function encodingLabel(v){return v==='line'?'仅线型':v==='marker'?'仅点型':v==='color-line'?'颜色 + 线型':v==='color-marker'?'颜色 + 点型':'仅颜色'}
function resultKey(r){return`${String(r.Factor1)}|${String(r.Factor2||'')}`}
function parseManualLetters(){const out={};String($('manualLetters').value||'').split(/[\n,，;；]+/).map(x=>x.trim()).filter(Boolean).forEach(item=>{const m=item.match(/^(.+?)\s*[=:：]\s*([A-Za-z]+\d*)$/);if(!m)return;let key=m[1].trim();if(!key.includes('|'))key=`${key}|`;out[key]=m[2]});return out}
function getSignificanceMap(metric,mode=$('significanceMode').value){if(mode==='none')return{};if(mode==='manual')return parseManualLetters();try{return Core.significanceLetters(state.analysis.samples,metric,state.design,{alpha:Number($('significanceAlpha').value)||.05,scope:$('significanceScope').value}).letters||{}}catch{return{}}}
function brokenVerticalSvg(x,top,plotBottom,baseY,sw,style){const gapStart=plotBottom+2,gapEnd=Math.min(baseY-2,plotBottom+20);let out=`<line x1="${x}" y1="${top}" x2="${x}" y2="${plotBottom}" stroke="#202020" stroke-width="${sw}"/>`;if(style==='zigzag')out+=`<path d="M${x},${gapStart} L${x-5},${gapStart+4} L${x+5},${gapStart+9} L${x-5},${gapStart+14} L${x},${gapEnd}" fill="none" stroke="#202020" stroke-width="${Math.max(1.5,sw)}" stroke-linejoin="miter"/>`;else out+=`<path d="M${x-6},${gapStart+1} L${x+6},${gapStart+11} M${x-6},${gapStart+8} L${x+6},${gapStart+18}" fill="none" stroke="#202020" stroke-width="${Math.max(1.5,sw)}"/>`;out+=`<line x1="${x}" y1="${gapEnd}" x2="${x}" y2="${baseY}" stroke="#202020" stroke-width="${sw}"/>`;return out}
function frameSvg(frame,left,right,top,plotBottom,baseY,sw,broken,breakStyle){if(frame==='none')return'';let out=`<line x1="${left}" y1="${baseY}" x2="${right}" y2="${baseY}" stroke="#202020" stroke-width="${sw}"/>`;out+=broken?brokenVerticalSvg(left,top,plotBottom,baseY,sw,breakStyle):`<line x1="${left}" y1="${top}" x2="${left}" y2="${baseY}" stroke="#202020" stroke-width="${sw}"/>`;if(frame==='full'){out+=`<line x1="${left}" y1="${top}" x2="${right}" y2="${top}" stroke="#202020" stroke-width="${sw}"/>`;out+=broken?brokenVerticalSvg(right,top,plotBottom,baseY,sw,breakStyle):`<line x1="${right}" y1="${top}" x2="${right}" y2="${baseY}" stroke="#202020" stroke-width="${sw}"/>`}return out}
function sampleValuesFor(r,metric){return state.analysis.samples.filter(s=>String(s.Factor1)===String(r.Factor1)&&String(s.Factor2||'')===String(r.Factor2||'')).map(s=>Number(s[metric])).filter(Number.isFinite)}
function splitLegendLabels(levels,unit){const manual=$('legendLabels').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),append=$('appendLegendUnit').checked;return levels.map((level,i)=>manual[i]||formatLegendLevel(level,append?unit:''))}
function formatLegendLevel(level,unit){const value=String(level),u=String(unit||'').trim();if(!u||value.includes(u))return value;return`${value} ${u}`}
function legendSvg(levels,colors,d,pos,W,H,M,size,lineWidth,markerSize,encoding,lineCap,baseY,titleTop){const labels=splitLegendLabels(levels,d.factors[1]?.unit||''),styles=levels.map((_,i)=>seriesStyle(i,encoding,colors)),showTitle=$('showLegendTitle').checked,title=showTitle?(d.factors[1]?.name||''):'';const itemWidths=labels.map(x=>Math.max(80,x.length*size*.7+50)),total=itemWidths.reduce((a,b)=>a+b,0)+(title?Math.max(65,title.length*size*.75+16):0);let x,y,out='';if(pos==='right'){x=W-M.r+18;y=M.t+8;if(title){out+=`<text x="${x}" y="${y}" font-size="${size}" font-weight="600">${escSvg(title)}</text>`;y+=21}levels.forEach((_,i)=>{out+=legendItemSvg(x,y,labels[i],styles[i],size,lineWidth,markerSize,lineCap);y+=24});return out}if(pos==='inside-top-right'){x=W-M.r-12;y=M.t+17;const width=Math.max(...itemWidths,100),height=levels.length*23+(title?23:8);out+=`<rect x="${x-width-12}" y="${y-16}" width="${width+18}" height="${height}" fill="white" fill-opacity=".92" stroke="#ddd"/>`;x=x-width;if(title){out+=`<text x="${x}" y="${y}" font-size="${size}" font-weight="600">${escSvg(title)}</text>`;y+=20}levels.forEach((_,i)=>{out+=legendItemSvg(x,y,labels[i],styles[i],size,lineWidth,markerSize,lineCap);y+=22});return out}const top=pos.startsWith('top-'),leftAlign=pos.endsWith('left'),rightAlign=pos.endsWith('right');y=top?(21+(titleTop?28:0)):(baseY+72);x=leftAlign?M.l:rightAlign?Math.max(M.l,W-M.r-total):Math.max(M.l,M.l+(W-M.l-M.r-total)/2);if(title){out+=`<text x="${x}" y="${y+size*.35}" font-size="${size}" font-weight="600">${escSvg(title)}</text>`;x+=Math.max(65,title.length*size*.75+16)}levels.forEach((_,i)=>{out+=legendItemSvg(x,y,labels[i],styles[i],size,lineWidth,markerSize,lineCap);x+=itemWidths[i]});return out}
function legendItemSvg(x,y,label,style,size,lineWidth,markerSize,lineCap){return`<line x1="${x}" y1="${y}" x2="${x+24}" y2="${y}" stroke="${style.color}" stroke-width="${lineWidth}" stroke-dasharray="${style.dash}" stroke-linecap="${lineCap}"/>${pointSvg(x+12,y,style.color,style.shape,Math.min(markerSize,3.8))}<text data-edit-target="legendLabels" class="editable-chart-text" x="${x+32}" y="${y+size*.35}" font-size="${size}">${escSvg(label)}</text>`}
function captionSvg(title,note,W,y,titleSize,noteSize){let out=`<text data-edit-target="chartTitle" class="editable-chart-text" x="${W/2}" y="${y}" text-anchor="middle" font-size="${titleSize}" font-weight="600" fill="#111">${escSvg(title)}</text>`;if(note)out+=`<text data-edit-target="captionNote" class="editable-chart-text" x="${W/2}" y="${y+22}" text-anchor="middle" font-size="${noteSize}" fill="#333">${escSvg(note)}</text>`;return out}
function bindChartTextEditing(){document.querySelectorAll('#chartCanvas [data-edit-target],#captionPreview [data-edit-target]').forEach(el=>el.addEventListener('click',()=>focusChartControl(el.dataset.editTarget)))}
function focusChartControl(id){const el=$(id);if(!el)return;const details=el.closest('details');if(details)details.open=true;el.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{el.focus();if(typeof el.select==='function')el.select()},250)}
function updateChartControlState(){const custom=$('yScaleMode')?.value==='custom';if($('yMin'))$('yMin').disabled=!custom;if($('yMax'))$('yMax').disabled=!custom;const multi=(state.design?.factorCount||state.factorCount)===2;['showLegend','legendPosition','appendLegendUnit','showLegendTitle','legendLabels','seriesEncoding','seriesDodge','dodgeDistance'].forEach(id=>{if($(id))$(id).disabled=!multi});if($('dodgeDistance'))$('dodgeDistance').disabled=!multi||$('seriesDodge').value==='none';if($('axisBreakStyle'))$('axisBreakStyle').disabled=!$('showAxisBreak').checked;if($('axisBreakGap'))$('axisBreakGap').disabled=!$('showAxisBreak').checked;if($('manualLettersWrap'))$('manualLettersWrap').classList.toggle('hidden',$('significanceMode').value!=='manual');if($('dashLineCap'))$('dashLineCap').disabled=!['line','color-line'].includes($('seriesEncoding').value);if(!multi&&$('significanceScope')&&['within-factor1','within-factor2'].includes($('significanceScope').value))$('significanceScope').value='auto'}
function resetChartSettings(){state.style='foodchem';const defaults={chartType:'auto',chartError:'sd',chartLanguage:state.design?.outputLanguage||'zh',figureWidth:'120',exportDpi:'300',titlePosition:'none',captionNote:'',yScaleMode:'auto',axisPadding:'6',yTickCount:'6',yDecimals:'auto',axisBreakStyle:'slash',axisBreakGap:'30',axisFrame:'left-bottom',axisLineWidth:'1.2',fontFamily:'Arial',titleFontSize:'12',axisFontSize:'13',tickFontSize:'11',legendFontSize:'10',lineWidth:'1.8',markerSize:'4.2',barWidth:'.62',legendPosition:'top-center',seriesEncoding:'color-marker',dashLineCap:'round',errorBarWidth:'1.2',errorCapWidth:'18',errorBarColorMode:'series',seriesDodge:'auto',dodgeDistance:'5',significanceMode:'auto',significanceScope:'auto',significanceAlpha:'.05',significanceOffset:'14'};Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});['chartTitle','xAxisTitle','yAxisTitle','yMin','yMax','legendLabels','manualLetters'].forEach(id=>{if($(id))$(id).value=''});$('showRawPoints').checked=false;$('showAxisBreak').checked=false;$('showGrid').checked=false;$('showLegend').checked=true;$('appendLegendUnit').checked=true;$('showLegendTitle').checked=false;$('useCustomColors').checked=false;renderStylePresets();updateChartControlState();renderChart();persist();toast('已恢复食品期刊推荐设置')}

function exportSvg(){const svg=$('paperChart');if(!svg)return;downloadBlob(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'}),fileBase()+'_图.svg')}
function exportPng(){const svg=$('paperChart');if(!svg)return;const text=new XMLSerializer().serializeToString(svg),blob=new Blob([text],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const dpi=Number($('exportDpi').value)||300,widthMm=Number($('figureWidth').value)||120,pixelWidth=Math.max(600,Math.round(widthMm/25.4*dpi)),vb=svg.getAttribute('viewBox').split(/\s+/).map(Number),ratio=vb[3]/vb[2],pixelHeight=Math.round(pixelWidth*ratio),canvas=document.createElement('canvas');canvas.width=pixelWidth;canvas.height=pixelHeight;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,pixelWidth,pixelHeight);ctx.drawImage(img,0,0,pixelWidth,pixelHeight);canvas.toBlob(b=>downloadBlob(b,fileBase()+`_图_${dpi}dpi.png`),'image/png');URL.revokeObjectURL(url)};img.src=url}
function exportCaption(){const p=$('captionPreview')?.querySelector('p');if(!p)return;downloadBlob(new Blob([p.textContent+'\r\n'],{type:'text/plain;charset=utf-8'}),fileBase()+'_图注.txt')}
function exportResultsCsv(){if(!state.analysis)return;const rows=Core.flattenResults(state.analysis.results,state.indicator),h=Object.keys(rows[0]),text='\ufeff'+[h.join(','),...rows.map(r=>h.map(k=>csvEscape(r[k])).join(','))].join('\r\n');downloadBlob(new Blob([text],{type:'text/csv;charset=utf-8'}),fileBase()+'_统计结果.csv')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escSvg(v){return esc(v)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
function persist(){const chartIds=['chartType','chartMetric','chartLanguage','chartError','figureWidth','exportDpi','titlePosition','chartTitle','captionNote','xAxisTitle','yAxisTitle','yScaleMode','axisPadding','yMin','yMax','yTickCount','yDecimals','axisBreakStyle','axisBreakGap','axisFrame','axisLineWidth','fontFamily','titleFontSize','axisFontSize','tickFontSize','legendFontSize','lineWidth','markerSize','barWidth','legendPosition','legendLabels','seriesEncoding','dashLineCap','errorBarWidth','errorCapWidth','errorBarColorMode','seriesDodge','dodgeDistance','significanceMode','significanceScope','significanceAlpha','significanceOffset','manualLetters','customColor1','customColor2','customColor3','customColor4','customColor5','customColor6'];const chart={};chartIds.forEach(id=>{if($(id))chart[id]=$(id).value});['showRawPoints','showAxisBreak','showGrid','showLegend','appendLegendUnit','showLegendTitle','useCustomColors'].forEach(id=>{if($(id))chart[id]=$(id).checked});const d={indicator:state.indicator,factorCount:state.factorCount,style:state.style,chart,fields:{experimentName:$('experimentName').value,sampleName:$('sampleName').value,factor1Name:$('factor1Name').value,factor1Type:$('factor1Type').value,factor1Unit:$('factor1Unit').value,factor1Levels:$('factor1Levels').value,factor2Name:$('factor2Name').value,factor2Type:$('factor2Type').value,factor2Unit:$('factor2Unit').value,factor2Levels:$('factor2Levels').value,parallelCount:$('parallelCount').value,measureCount:$('measureCount').value}};localStorage.setItem('foodlab-v025',JSON.stringify(d));$('saveStatus').textContent='已保存';clearTimeout(persist.timer);persist.timer=setTimeout(()=>$('saveStatus').textContent='本地自动保存',900)}
function restore(){try{const d=JSON.parse(localStorage.getItem('foodlab-v025')||localStorage.getItem('foodlab-v024')||localStorage.getItem('foodlab-v023')||localStorage.getItem('freshness-v02')||'null');if(!d){resetChartSettings();return}state.indicator=d.indicator||'pH';state.style=d.style||'nature';for(const[k,v]of Object.entries(d.fields||{}))if($(k))$(k).value=v;for(const[k,v]of Object.entries(d.chart||{}))if($(k)){if(typeof v==='boolean')$(k).checked=v;else $(k).value=v}if(d.chart?.showTitle===false&&!d.chart?.titlePosition&&$('titlePosition'))$('titlePosition').value='none';if(!$('titlePosition').value)$('titlePosition').value='none';setFactorCount(d.factorCount||1);renderStylePresets();updateMetricOptions();updateChartControlState()}catch{resetChartSettings()}}
init();
