'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const templates={
 foodchem:{font:'Arial',axis:1.35,colors:['#2f6b2f','#d0832f','#4b6668','#4c78a8','#b35c44'],grid:false},
 meatsci:{font:'Arial',axis:1.25,colors:['#98c97a','#75b66a','#4d9253','#80b8db','#3b8fc1'],grid:false},
 nature:{font:'Arial',axis:1.2,colors:['#3C5488','#E64B35','#00A087','#4DBBD5','#F39B7F'],grid:false},
 mono:{font:'Arial',axis:1.4,colors:['#111','#555','#888','#aaa','#333'],grid:false}
};
const demoLine=`x\tgroup\tmean\tsd\tletter\n0\t4 °C\t5.60\t0.02\ta\n0\t-1 °C\t5.59\t0.02\ta\n0\t-18 °C\t5.58\t0.02\ta\n2\t4 °C\t5.67\t0.02\ta\n2\t-1 °C\t5.65\t0.02\tab\n2\t-18 °C\t5.63\t0.02\tb\n4\t4 °C\t5.74\t0.02\ta\n4\t-1 °C\t5.71\t0.02\tab\n4\t-18 °C\t5.69\t0.02\tb\n6\t4 °C\t5.81\t0.02\ta\n6\t-1 °C\t5.78\t0.02\tab\n6\t-18 °C\t5.75\t0.02\tb\n8\t4 °C\t5.88\t0.02\ta\n8\t-1 °C\t5.85\t0.02\tab\n8\t-18 °C\t5.81\t0.02\tb\n10\t4 °C\t5.95\t0.02\ta\n10\t-1 °C\t5.92\t0.02\tab\n10\t-18 °C\t5.88\t0.02\tb`;
const demoBar=`x\tgroup\tmean\tsd\tletter\n0-5\tA\t75.1\t0.35\tde\n0-15\tA\t77.4\t0.28\tabc\n0-25\tA\t76.9\t0.31\tabc\n3-5\tA\t75.2\t0.30\tde\n3-15\tA\t76.2\t0.29\tcd\n3-25\tA\t78.1\t0.34\ta\n6-5\tB\t74.4\t0.26\te\n6-15\tB\t76.5\t0.24\tbc\n6-25\tB\t77.3\t0.27\tab\n9-5\tB\t74.6\t0.25\te\n9-15\tB\t75.7\t0.29\tcd\n9-25\tB\t76.0\t0.30\tcd`;
const state={view:'home',chartType:'line',breakAxis:false,selected:'axis-y',legend:{x:735,y:62},data:[],settings:{title:'双因素变化图',xTitle:'储藏时间 (d)',yTitle:'指标值',axisColor:'#20262b',axisWidth:1.35,tickSize:12,font:'Arial',lineWidth:2.2,markerSize:4.6,errorWidth:1.15,errorCap:10,legendSize:12,legendVisible:true,letters:true,letterSize:11,barGap:3,barOpacity:.95,yMin:null,yMax:null,lowerMax:20,upperMin:70}};
function init(){bindNav();bindUi();$('#dataText').value=demoLine;parseData();showView('home');}
function bindNav(){ $$('#mainNav .nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view)); $$('.module-card').forEach(b=>b.onclick=()=>showView(b.dataset.open)); $('#openChartBtn').onclick=()=>showView('chart'); }
function showView(v){state.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const map={home:['分析总览','按分析任务组织，而不是按实验指标拆分。'],data:['数据中心','通用长表可供单因素、双因素和多变量分析共同使用。'],basic:['基础统计','描述统计与数据质量检查。'],anova:['显著性分析','统一管理假设检验和显著性字母。'],chart:['论文图工作台','点击图中对象直接编辑属性。'],multivar:['PCA / PLS-DA','多变量降维和监督分类。'],cluster:['HCA / 热图','层次聚类、树状图和热图。'],correlation:['相关性分析','相关系数、热图与网络。'],regression:['回归分析','回归建模与诊断。'],export:['论文输出','统一导出图、表和图注。']};$('#pageTitle').textContent=map[v][0];$('#pageSubtitle').textContent=map[v][1];if(v==='chart')render();}
function bindUi(){
 $('#loadLineDemo').onclick=()=>{$('#dataText').value=demoLine;state.chartType='line';state.breakAxis=false;parseData();toast('已载入折线示例')};
 $('#loadBarDemo').onclick=()=>{$('#dataText').value=demoBar;state.chartType='bar';state.breakAxis=true;state.settings.title='Moisture content';state.settings.xTitle='Treatment';state.settings.yTitle='Moisture content (%)';parseData();toast('已载入断轴柱状图示例')};
 $('#clearData').onclick=()=>{$('#dataText').value='';state.data=[]};
 $('#renderFromData').onclick=()=>{parseData();render();};
 $$('[data-chart-type]').forEach(b=>b.onclick=()=>{state.chartType=b.dataset.chartType;$$('[data-chart-type]').forEach(x=>x.classList.toggle('active',x===b));render()});
 $('#toggleBreak').onclick=()=>{state.breakAxis=!state.breakAxis;render()};
 $('#journalTemplate').onchange=e=>{applyTemplate(e.target.value);render()};
 $('#exportSvg').onclick=exportSvg;$('#exportPng').onclick=exportPng;
}
function parseData(){const text=$('#dataText').value.trim();if(!text){state.data=[];return}const lines=text.split(/\r?\n/).filter(Boolean),sep=lines[0].includes('\t')?'\t':',';const h=lines[0].split(sep).map(x=>x.trim().toLowerCase());state.data=lines.slice(1).map(line=>{const p=line.split(sep).map(x=>x.trim()),o={};h.forEach((k,i)=>o[k]=p[i]??'');return{x:o.x,group:o.group||'Series 1',mean:Number(o.mean),sd:Number(o.sd||0),letter:o.letter||''}}).filter(r=>r.x&&Number.isFinite(r.mean));}
function applyTemplate(name){const t=templates[name];state.settings.font=t.font;state.settings.axisWidth=t.axis;state.palette=t.colors;}
function groups(){return [...new Set(state.data.map(d=>d.group))]}
function xs(){return [...new Set(state.data.map(d=>d.x))]}
function render(){parseData();$('#toggleBreak').textContent=`断轴：${state.breakAxis?'开':'关'}`;$$('[data-chart-type]').forEach(x=>x.classList.toggle('active',x.dataset.chartType===state.chartType));renderLayers();renderChart();renderProperties();}
function renderLayers(){const layers=[['title','标题'],['legend','图例'],['axis-y','Y 轴'],['axis-x','X 轴'],['series','数据系列'],['error','误差棒'],['letters','显著性字母'],['background','背景']];$('#layersList').innerHTML=layers.map(([id,n])=>`<button class="layer-item ${state.selected===id?'active':''}" data-layer="${id}"><span class="layer-dot"></span>${n}</button>`).join('');$$('[data-layer]').forEach(b=>b.onclick=()=>selectObject(b.dataset.layer));}
function selectObject(id){state.selected=id;renderLayers();renderProperties();$$('.chart-object').forEach(x=>x.classList.toggle('object-selected',x.dataset.object===id));}
function chartBounds(){const vals=state.data.flatMap(d=>[d.mean-d.sd,d.mean+d.sd]);let min=Math.min(...vals),max=Math.max(...vals);if(!Number.isFinite(min)){min=0;max=1}const pad=(max-min||1)*.1;return{min:state.settings.yMin??(min-pad),max:state.settings.yMax??(max+pad)}}
function renderChart(){const W=920,H=610,M={l:92,r:56,t:65,b:95}, plotW=W-M.l-M.r, plotH=H-M.t-M.b;const font=state.settings.font,colors=state.palette||templates[$('#journalTemplate').value].colors;let svg=`<svg id="paperSvg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="920" height="610" style="font-family:${font}"><rect data-object="background" class="chart-object" x="0" y="0" width="${W}" height="${H}" fill="white"/>`;
 svg+=`<text data-object="title" class="chart-object" x="${W/2}" y="34" text-anchor="middle" font-size="17" font-weight="600">${esc(state.settings.title)}</text>`;
 if(!state.data.length){svg+=`<text x="${W/2}" y="${H/2}" text-anchor="middle" fill="#87939c">请在数据中心粘贴数据</text></svg>`;$('#chartStage').innerHTML=svg;return}
 const xvals=xs(),gs=groups(),b=chartBounds();
 if(state.breakAxis&&state.chartType==='bar')svg+=renderBrokenBar(W,H,M,plotW,plotH,xvals,gs,colors);else svg+=renderNormal(W,H,M,plotW,plotH,xvals,gs,colors,b);
 svg+=renderLegend(gs,colors);svg+='</svg>';$('#chartStage').innerHTML=svg;bindChartObjects();bindLegendDrag();}
function renderNormal(W,H,M,plotW,plotH,xvals,gs,colors,b){const y=v=>M.t+(b.max-v)/(b.max-b.min)*plotH,xStep=plotW/xvals.length;let out='';const ticks=6;for(let i=0;i<ticks;i++){const v=b.min+(b.max-b.min)*i/(ticks-1),yy=y(v);out+=`<line x1="${M.l-6}" x2="${M.l}" y1="${yy}" y2="${yy}" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}"/><text x="${M.l-11}" y="${yy+4}" text-anchor="end" font-size="${state.settings.tickSize}">${fmt(v)}</text>`}
 out+=axisPaths(W,H,M,plotW,plotH);out+=`<text data-object="axis-x" class="chart-object" x="${M.l+plotW/2}" y="${H-28}" text-anchor="middle" font-size="15">${esc(state.settings.xTitle)}</text><text data-object="axis-y" class="chart-object" transform="translate(27 ${M.t+plotH/2}) rotate(-90)" text-anchor="middle" font-size="15">${esc(state.settings.yTitle)}</text>`;
 xvals.forEach((x,i)=>out+=`<text x="${M.l+(i+.5)*xStep}" y="${M.t+plotH+27}" text-anchor="middle" font-size="${state.settings.tickSize}">${esc(x)}</text>`);
 if(state.chartType==='line'){
  gs.forEach((g,gi)=>{const pts=xvals.map((x,i)=>state.data.find(d=>d.x===x&&d.group===g)).filter(Boolean);const coords=pts.map(d=>[M.l+(xvals.indexOf(d.x)+.5)*xStep,y(d.mean)]);out+=`<path data-object="series" class="chart-object" d="${coords.map((p,i)=>(i?'L':'M')+p[0]+','+p[1]).join(' ')}" fill="none" stroke="${colors[gi%colors.length]}" stroke-width="${state.settings.lineWidth}" stroke-linejoin="round"/>`;pts.forEach(d=>{const xx=M.l+(xvals.indexOf(d.x)+.5)*xStep,yy=y(d.mean),e=Math.abs(y(d.mean+d.sd)-yy);out+=errorSvg(xx,yy,e,colors[gi%colors.length]);out+=`<circle data-object="series" class="chart-object" cx="${xx}" cy="${yy}" r="${state.settings.markerSize}" fill="white" stroke="${colors[gi%colors.length]}" stroke-width="${Math.max(1.6,state.settings.lineWidth*.75)}"/>`;if(state.settings.letters&&d.letter)out+=letterSvg(xx,yy-e-9,d.letter)})})
 }else{
  const groupW=xStep*.72,barW=groupW/gs.length; xvals.forEach((x,i)=>gs.forEach((g,gi)=>{const d=state.data.find(r=>r.x===x&&r.group===g);if(!d)return;const xx=M.l+(i+.5)*xStep-groupW/2+gi*barW+state.settings.barGap/2,yy=y(d.mean),base=y(Math.max(0,b.min)),h=base-yy;out+=`<rect data-object="series" class="chart-object" x="${xx}" y="${yy}" width="${barW-state.settings.barGap}" height="${Math.max(0,h)}" fill="${colors[gi%colors.length]}" fill-opacity="${state.settings.barOpacity}"/>`;const cx=xx+(barW-state.settings.barGap)/2,e=Math.abs(y(d.mean+d.sd)-yy);out+=errorSvg(cx,yy,e,colors[gi%colors.length]);if(state.settings.letters&&d.letter)out+=letterSvg(cx,yy-e-9,d.letter)}));
 }
 return out;}
function renderBrokenBar(W,H,M,plotW,plotH,xvals,gs,colors){const gap=22,lowerH=110,upperH=plotH-lowerH-gap,lowerTop=M.t+upperH+gap,axisY=M.t+plotH;const loMax=state.settings.lowerMax,hiMin=state.settings.upperMin;const max=Math.max(...state.data.map(d=>d.mean+d.sd))*1.03;const yUpper=v=>M.t+(max-v)/(max-hiMin)*upperH,yLower=v=>lowerTop+(loMax-v)/loMax*lowerH,xStep=plotW/xvals.length;let out='';
 // continuous-looking left axis with aligned slash break marks
 out+=`<g data-object="axis-y" class="chart-object" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}" fill="none" stroke-linecap="square"><path d="M${M.l},${M.t} V${M.t+upperH}"/><path d="M${M.l},${lowerTop} V${axisY}"/><path d="M${M.l-7},${M.t+upperH+8} l14,14 M${M.l-7},${M.t+upperH+15} l14,14"/></g>`;
 out+=`<g data-object="axis-x" class="chart-object" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}" fill="none"><path d="M${M.l},${axisY} H${M.l+plotW}"/></g>`;
 // right frame broken at exact same heights
 out+=`<g stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}" fill="none"><path d="M${M.l+plotW},${M.t} V${M.t+upperH}"/><path d="M${M.l+plotW},${lowerTop} V${axisY}"/><path d="M${M.l+plotW-7},${M.t+upperH+8} l14,14 M${M.l+plotW-7},${M.t+upperH+15} l14,14"/><path d="M${M.l},${M.t} H${M.l+plotW}"/></g>`;
 // ticks
 [0,10,20].forEach(v=>{const yy=yLower(v);out+=`<line x1="${M.l-6}" x2="${M.l}" y1="${yy}" y2="${yy}" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}"/><text x="${M.l-11}" y="${yy+4}" text-anchor="end" font-size="${state.settings.tickSize}">${v}</text>`});
 const upperTicks=[hiMin,hiMin+5,hiMin+10].filter(v=>v<=max+1);upperTicks.forEach(v=>{const yy=yUpper(v);out+=`<line x1="${M.l-6}" x2="${M.l}" y1="${yy}" y2="${yy}" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}"/><text x="${M.l-11}" y="${yy+4}" text-anchor="end" font-size="${state.settings.tickSize}">${v}</text>`});
 out+=`<text data-object="axis-x" class="chart-object" x="${M.l+plotW/2}" y="${H-28}" text-anchor="middle" font-size="15">${esc(state.settings.xTitle)}</text><text data-object="axis-y" class="chart-object" transform="translate(27 ${M.t+plotH/2}) rotate(-90)" text-anchor="middle" font-size="15">${esc(state.settings.yTitle)}</text>`;
 const groupW=xStep*.72,barW=groupW/gs.length;xvals.forEach((x,i)=>{out+=`<text x="${M.l+(i+.5)*xStep}" y="${axisY+27}" text-anchor="middle" font-size="${state.settings.tickSize}" transform="rotate(-90 ${M.l+(i+.5)*xStep} ${axisY+27})">${esc(x)}</text>`;gs.forEach((g,gi)=>{const d=state.data.find(r=>r.x===x&&r.group===g);if(!d)return;const xx=M.l+(i+.5)*xStep-groupW/2+gi*barW+state.settings.barGap/2,w=barW-state.settings.barGap,c=colors[gi%colors.length];const lowerValue=Math.min(d.mean,loMax),ly=yLower(lowerValue),lh=axisY-ly;if(lh>0)out+=`<rect data-object="series" class="chart-object" x="${xx}" y="${ly}" width="${w}" height="${lh}" fill="${c}" fill-opacity="${state.settings.barOpacity}"/>`;if(d.mean>=hiMin){const uy=yUpper(d.mean),uh=M.t+upperH-uy;out+=`<rect data-object="series" class="chart-object" x="${xx}" y="${uy}" width="${w}" height="${uh}" fill="${c}" fill-opacity="${state.settings.barOpacity}"/>`;const cx=xx+w/2,e=Math.abs(yUpper(d.mean+d.sd)-uy);out+=errorSvg(cx,uy,e,c);if(state.settings.letters&&d.letter)out+=letterSvg(cx,uy-e-8,d.letter)}})});return out;}
function axisPaths(W,H,M,plotW,plotH){return`<g data-object="axis-y" class="chart-object" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}" fill="none"><path d="M${M.l},${M.t} V${M.t+plotH}"/></g><g data-object="axis-x" class="chart-object" stroke="${state.settings.axisColor}" stroke-width="${state.settings.axisWidth}" fill="none"><path d="M${M.l},${M.t+plotH} H${M.l+plotW}"/></g>`}
function errorSvg(x,y,e,c){return`<g data-object="error" class="chart-object" stroke="${c}" stroke-width="${state.settings.errorWidth}"><line x1="${x}" x2="${x}" y1="${y-e}" y2="${y+e}"/><line x1="${x-state.settings.errorCap/2}" x2="${x+state.settings.errorCap/2}" y1="${y-e}" y2="${y-e}"/><line x1="${x-state.settings.errorCap/2}" x2="${x+state.settings.errorCap/2}" y1="${y+e}" y2="${y+e}"/></g>`}
function letterSvg(x,y,t){return`<text data-object="letters" class="chart-object" x="${x}" y="${y}" text-anchor="middle" font-size="${state.settings.letterSize}" font-weight="600">${esc(t)}</text>`}
function renderLegend(gs,colors){if(!state.settings.legendVisible)return'';const x=state.legend.x,y=state.legend.y;let out=`<g id="legendGroup" data-object="legend" class="chart-object" transform="translate(${x} ${y})">`;gs.forEach((g,i)=>{const yy=i*25,c=colors[i%colors.length];if(state.chartType==='bar')out+=`<rect x="0" y="${yy-9}" width="18" height="13" fill="${c}"/><text x="28" y="${yy+2}" font-size="${state.settings.legendSize}">${esc(g)}</text>`;else out+=`<line x1="0" x2="23" y1="${yy}" y2="${yy}" stroke="${c}" stroke-width="${state.settings.lineWidth}"/><circle cx="11.5" cy="${yy}" r="${state.settings.markerSize}" fill="white" stroke="${c}" stroke-width="1.7"/><text x="32" y="${yy+4}" font-size="${state.settings.legendSize}">${esc(g)}</text>`});return out+'</g>'}
function bindChartObjects(){$$('#chartStage .chart-object').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();selectObject(el.dataset.object)}));}
function bindLegendDrag(){const el=$('#legendGroup'),svg=$('#paperSvg');if(!el||!svg)return;let start=null;el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);start={px:e.clientX,py:e.clientY,x:state.legend.x,y:state.legend.y};el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!start)return;const r=svg.getBoundingClientRect(),sx=920/r.width,sy=610/r.height;state.legend.x=start.x+(e.clientX-start.px)*sx;state.legend.y=start.y+(e.clientY-start.py)*sy;el.setAttribute('transform',`translate(${state.legend.x} ${state.legend.y})`)});el.addEventListener('pointerup',()=>{start=null;el.classList.remove('dragging')});}
function renderProperties(){const id=state.selected,names={'axis-y':'Y 轴','axis-x':'X 轴',series:'数据系列',error:'误差棒',legend:'图例',letters:'显著性字母',title:'标题',background:'背景'};$('#selectedObjectName').textContent=names[id]||'未选择对象';let html='';if(id==='axis-y')html=fields([{k:'yTitle',n:'轴标题',t:'text'},{k:'yMin',n:'最小值',t:'number',nullable:true},{k:'yMax',n:'最大值',t:'number',nullable:true},{k:'axisWidth',n:'轴线粗细',t:'range',min:.5,max:3,step:.1},{k:'axisColor',n:'轴线颜色',t:'color'},{k:'tickSize',n:'刻度字号',t:'range',min:8,max:20,step:1}])+breakFields();else if(id==='axis-x')html=fields([{k:'xTitle',n:'轴标题',t:'text'},{k:'axisWidth',n:'轴线粗细',t:'range',min:.5,max:3,step:.1},{k:'axisColor',n:'轴线颜色',t:'color'},{k:'tickSize',n:'刻度字号',t:'range',min:8,max:20,step:1}]);else if(id==='series')html=fields([{k:'lineWidth',n:'线条/边框粗细',t:'range',min:.5,max:5,step:.1},{k:'markerSize',n:'点大小',t:'range',min:2,max:9,step:.2},{k:'barGap',n:'柱间距',t:'range',min:0,max:12,step:1},{k:'barOpacity',n:'填充透明度',t:'range',min:.2,max:1,step:.05}])+paletteEditor();else if(id==='error')html=fields([{k:'errorWidth',n:'误差棒粗细',t:'range',min:.5,max:4,step:.1},{k:'errorCap',n:'端帽宽度',t:'range',min:3,max:25,step:1}]);else if(id==='legend')html=check('legendVisible','显示图例')+fields([{k:'legendSize',n:'图例字号',t:'range',min:8,max:20,step:1}])+`<div class="hint">可直接拖动图例位置。柱状图显示色块，折线图显示线＋点。</div>`;else if(id==='letters')html=check('letters','显示显著性字母')+fields([{k:'letterSize',n:'字母字号',t:'range',min:8,max:20,step:1}])+`<div class="hint">字母读取数据表中的 letter 列。</div>`;else if(id==='title')html=fields([{k:'title',n:'图题',t:'text'}]);else if(id==='background')html=`<div class="hint">当前论文模板使用白色背景，避免不必要的装饰。</div>`;$('#propertyEditor').innerHTML=html||'<div class="empty-state">在图中点击一个对象</div>';bindPropertyInputs();}
function fields(arr){return arr.map(f=>`<div class="field"><label><span>${f.n}</span><output data-out="${f.k}">${state.settings[f.k]??''}</output></label><input data-setting="${f.k}" type="${f.t}" ${f.min!=null?`min="${f.min}"`:''} ${f.max!=null?`max="${f.max}"`:''} ${f.step!=null?`step="${f.step}"`:''} value="${state.settings[f.k]??''}"></div>`).join('')}
function check(k,n){return`<label class="check-row"><input type="checkbox" data-setting="${k}" ${state.settings[k]?'checked':''}>${n}</label>`}
function breakFields(){return`<label class="check-row"><input id="breakFromProp" type="checkbox" ${state.breakAxis?'checked':''}>启用断轴</label><div class="two-col">${fields([{k:'lowerMax',n:'下段最大值',t:'number'},{k:'upperMin',n:'上段最小值',t:'number'}])}</div>`}
function paletteEditor(){const colors=state.palette||templates[$('#journalTemplate').value].colors;return`<div class="field"><label>系列配色</label><div class="two-col">${colors.slice(0,4).map((c,i)=>`<input type="color" data-palette="${i}" value="${c}">`).join('')}</div></div>`}
function bindPropertyInputs(){$$('[data-setting]').forEach(el=>el.oninput=()=>{const k=el.dataset.setting;let v=el.type==='checkbox'?el.checked:el.value;if(el.type==='range'||el.type==='number')v=el.value===''?null:Number(el.value);state.settings[k]=v;const o=$(`[data-out="${k}"]`);if(o)o.textContent=v??'';renderChart()});$$('[data-palette]').forEach(el=>el.oninput=()=>{state.palette=state.palette||[...templates[$('#journalTemplate').value].colors];state.palette[Number(el.dataset.palette)]=el.value;renderChart()});const br=$('#breakFromProp');if(br)br.onchange=()=>{state.breakAxis=br.checked;render()};}
function exportSvg(){const svg=$('#paperSvg');if(!svg)return;download(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'}),'FoodLab_figure.svg')}
function exportPng(){const svg=$('#paperSvg');if(!svg)return;const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1840;c.height=1220;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download(b,'FoodLab_figure.png'));URL.revokeObjectURL(url)};img.src=url}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v){const a=Math.abs(v);return a>=100?v.toFixed(0):a>=10?v.toFixed(1):v.toFixed(2)}
init();
